### ISSUE TITLE
Wrong behaviour when validating conditional properties

### ISSUE THREAD

**Issue by dadiego91** [python-jsonschema/jsonschema#1000]
Let's suppose we define the following schema:

```
SCHEMA = {
    "type": "object",
    "properties": {
        "name": {
            "enum": ["D", "B"],
        },
    },
    "if": {
        "properties": {
            "name": {"const": "B"},
        },
    },
    "then": {
        "required": ["id"],
    },
}
```
Note that "name" property is not mandatory, but if passing it, it can only take two values. If "B", then a new property called "id" should be required. Nevertheless, the following happens:

```
import jsonschema

payload1 = {"name": "D"}    # this success, as expected
payload2 = {"name": "B"}    # this fails, as expected
payload3 = {}    # this is failing, but actually it shouldn't fail

for payload in (payload1, payload2, payload3):
    jsonschema.validate(payload, SCHEMA)
```

Why payload3 does not pass the validation? as name is not "B" it should not request an "id" key, but id does

**Comment by Julian** [comment]
Precisely because as you mentioned, name isn't being made required, so {} is valid under the if schema as it contains no `name`. Perhaps you mean to add `required: [name]` to your if schema.

**Comment by Julian** [comment]
Hope the above helps, if not feel free to follow up in a discussion.
