### ISSUE TITLE
How to limit the size of ValidationError when validating very big instance

### ISSUE THREAD

**Issue by nodje** [python-jsonschema/jsonschema#1001]
Hi,
basically my issue fits in the title.

The ValidationError object reported is too big.
And understandably because the instance it validates is ~50Mb.

I was hoping there was a way to limit the error reporting, even if it means getting less context.

Worst case scenario, I would be happy with "This json instance is not valid"

**Comment by Julian** [comment]
Hi -- please use the Discussions board (or Slack) for questions.

In short, you can catch the exception if you'd like, and print whatever message you'd like. See https://python-jsonschema.readthedocs.io/en/stable/errors/ for further details on what's available.
