### ISSUE TITLE
contentEncoding is not working

### ISSUE THREAD

**Issue by upright-hanyang** [python-jsonschema/jsonschema#1004]
Hi, I am studying JsonSchema using your library. Thanks for making this useful library.

In the content section(https://json-schema.org/understanding-json-schema/reference/non_json_data.html)
, I try to validate a string  using contentEncoding.

I think an error should occur in the second verification. (because  -, % does not exist in base64)
![image](https://user-images.githubusercontent.com/61227354/193779322-f56ef47b-ae9f-4605-bc21-bb41e8b5c66e.png)

But none of the error occurred. Am i missing something?

**Comment by Julian** [comment]
Content encoding in the JSON Schema specifications isn't an assertion (meaning it doesn't affect the result of validating), it's purely informational.

**Comment by upright-hanyang** [comment]
Oh, I see. Thank you for quick response. I close this issue.
