### ISSUE TITLE
Feature Request: Offline Validation with CLI

### ISSUE THREAD

**Issue by nikstur** [python-jsonschema/jsonschema#1007]
I'm looking to use jsonschema in Nix (as in NixOS) tests to validate whether an application generates valid JSON documents. All Nix tests, however, run in a sandbox that has no network access to enable reproducible builds.

Would it be a good idea/feasible to add a flag to the command line that disables resolving remote references at all?

I understand that this would mean that the JSON document could only be partially validated but that's a tradeoff I'm willing to make.

**Comment by Julian** [comment]
Hi there! Yes this is certainly a good idea, though the CLI is slated for deprecation (#600) and is being replaced by https://github.com/python-jsonschema/check-jsonschema -- it's already more featureful, can you have a look, it may support this already, but if not file an issue there?

**Comment by nikstur** [comment]
I'll defineteley check it out. Thanks for the quick response! I'll close this issue and open one in the other repo if it doesn't already solve my problem.
