### ISSUE TITLE
problem with oneof

### ISSUE THREAD

**Issue by wolframhaussig** [python-jsonschema/jsonschema#1013]
I am trying to build a JSON schema according to our needs and I have a problem with the usage of `oneof` - maybe you can explain what I am doing wrong or if this is a bug/missing feature:
I have a simple JSON like this (of course it is reduced to explain the problem):
```json
{
    "@timestamp": "2016-05-23T08:05:34.853Z",
    "ecs": {
        "version": "8.5.1"
    },
    "tags": [1, 2, 3]
}
```
The schema looks like this:
```json
{
    "$id": "http://www.test.com",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$comment": "Autogenerated schema",
    "type": "object",
    "properties": {
        "tags": {
            "oneof": [{
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }, {
                    "type": "string"
                }
            ],
            "description": "List of keywords used to tag each event.",
            "title": "List of keywords used to tag each event.",
            "examples": ["[\"production\", \"env2\"]"]
        }
    }
}
```
My call to validate:
`validate(instance={"@timestamp" : "2016-05-23T08:05:34.853Z", "ecs" : { "version": "8.5.1"}, "tags": [1,2,3]}, schema=RunSchemaArrayTests.schema, format_checker=FormatChecker())`

Now, I would expect to get an error because `tags` should be either a string or an array of strings but the validation succeeds. If I remove `oneof` to only allow an array of strings the validation generates an error as I would expect.

Can you explain why the validation does not check the type of the tags entries?

Background:  
We are using the Elastic Stack and are trying to generate a JSON schema based on our fields. As Elasticsearch does not differentiate between arrays and single values we want to allow both in the incoming messages.

**Comment by Julian** [comment]
Hi -- it's spelled `oneOf`, capital O.

**Comment by wolframhaussig** [comment]
Oh my god - I am so sorry...

**Comment by Julian** [comment]
All good!
