### ISSUE TITLE
Not getting specific error messages from nested objects

### ISSUE THREAD

**Issue by beck3905** [python-jsonschema/jsonschema#1014]
I have the following schema

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "intersects": {
      "type": ["string", "object"]
    },
    "bbox": {
      "type": "array",
      "items": {
        "type": "number",
        "minItems": 4,
        "maxItems": 4
      },
    },
    "query": {
      "type": "object"
    },
    "actions": {
      "type": "array",
      "items": {
        "oneOf": [{
            "$ref": "#/$definitions/order"
          },
          {
            "$ref": "#/$definitions/notify"
          },
        ]
      },
    },
  },
  "anyOf": [{
      "required": ["intersects", "actions"]
    },
    {
      "required": ["bbox", "actions"]
    },
  ],
  "additionalProperties": False,
  "$definitions": {
    "order": {
      "type": "object",
      "properties": {
        "action": {
          "const": "order"
        },
        "metadata": {
          "type": "object"
        },
        "notifications": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "enum": ["email", "sns"],
              },
              "address": {
                "type": "string"
              },
              "topic_arn": {
                "type": "string"
              },
              "verbose": {
                "type": "boolean"
              },
            },
            "required": ["type"],
            "additionalProperties": False,
          },
        },
      },
      "required": ["action", "output_config"],
      "additionalProperties": False,
    },
    "notify": {
      "type": "object",
      "properties": {
        "action": {
          "const": "notify"
        },
        "notifications": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "enum": ["email", "sns"],
              },
              "address": {
                "type": "string"
              },
              "topic_arn": {
                "type": "string"
              },
              "verbose": {
                "type": "boolean"
              },
            },
            "required": ["type"],
            "additionalProperties": False,
          },
        },
      },
      "required": ["action", "notifications"],
      "additionalProperties": False,
    },
  },
}
```

I am using `iter_errors` and `ErrorTree` to get a list of all error messages recursively.

```
def handle_error_tree(tree):

    error_messages = []
    if tree.errors:

        for error in tree.errors.values():

            if error.message:
                error_messages.append(f"{error.json_path}: {error.message}")

    for child in tree:
        error_messages.extend(handle_error_tree(tree[child]))

    return error_messages

body_errors = validator.iter_errors(body)
error_tree = ErrorTree(body_errors)
error_messages = handle_error_tree(error_tree)
```

When my `body` is 
```
{
    "query": 10,
    "test": True,
    "actions": [{"action": "notify", "foo": True}],
}
```

These are the `error_messages`:

```
[
    "$: {'query': 10, 'test': True, 'actions': [{'action': 'notify', 'foo': True}]} is not valid under any of the given schemas",
    "$: Additional properties are not allowed ('test' was unexpected)",
    "$.query: 10 is not of type 'object'",
    "$.actions[0]: {'action': 'notify', 'foo': True} is not valid under any of the given schemas",
]
```

The top level `anyOf` validator for required fields reports "$: {'query': 10, 'test': True, 'actions': [{'action': 'notify', 'foo': True}]} is not valid under any of the given schemas" and then has a child `ErrorTree` that reports "$.query: 10 is not of type 'object'".  However, the `oneOf` under the `actions` property only reports "$.actions[0]: {'action': 'notify', 'foo': True} is not valid under any of the given schemas", but doesn't have a child `ErrorTree` or additional messages about the additional `foo` property.

It seems like maybe some level of recursion in the validation logic is missing.  I expected to see both the `oneOf` validation message, but then more detailed messages about why it doesn't match `oneOf` the schemas.  I'm not sure if this is related to using `$ref`s or if it is due to the nested structure of the schema.

**Comment by Julian** [comment]
Errors from within the `oneOf` are found in the [context attribute](https://python-jsonschema.readthedocs.io/en/stable/errors/#jsonschema.exceptions.ValidationError.context) of the `oneOf` error.

**Comment by beck3905** [comment]
> Errors from within the `oneOf` are found in the [context attribute](https://python-jsonschema.readthedocs.io/en/stable/errors/#jsonschema.exceptions.ValidationError.context) of the `oneOf` error.

Why is that different than an `anyOf`?

**Comment by Julian** [comment]
It isn't, they're both the same, both have their suberrors in `.context`.

**Comment by beck3905** [comment]
So in my `handle_error_tree` method above, do you think it would be reasonable to update it to
```
def handle_error_tree(tree):

    error_messages = []
    if tree.errors:

        for error in tree.errors.values():
            
            if error.context:
                 for sub_error in error.context:
                     error_messages.append(f"{error.json_path}: {error.message}")
            elif error.message:
                error_messages.append(f"{error.json_path}: {error.message}")

    for child in tree:
        error_messages.extend(handle_error_tree(tree[child]))

    return error_messages
```

Can those subschema errors have children?

**Comment by Julian** [comment]
I'm not sure what your `handle_error_tree` function is trying to do semantically so I can't answer that, it's kind of dependent on what you mean for it to do -- yes, schemas can contain arbitrarily nested subschemas, and if those are `anyOf` or `oneOf` you can go on indefinitely there.

**Comment by beck3905** [comment]
Basically, my goal is to report all the specific error messages in a list for all the different schema validation errors present.  I've found that using the best match functionality within the `validate` method often led to confusing messages especially when dealing with `anyOf` or `oneOf` so I felt it better to just report all of them so that my end user knows what needs to be fixed in their JSON body.  So my goal with `handle_error_tree` is to simply gather all the various error messages present in the tree.

**Comment by Julian** [comment]
That kind of thing produces even more confusing messages typically. But if you want to recurse arbitrarily, keep going until you stop seeing `.context` attributes with errors in them essentially.

There are also a few best_match enhancing issues open which PRs would improve things for definitely!

**Comment by beck3905** [comment]
Would errors in the `.context` also have children?  So for example, I obviously can do
```
for sub_error in error.context:
```
but should I also do
```
for child in sub_error:
```
like I did with the `ErrorTree`?  I think I'm getting confused by the multiple branches of recursion.

**Comment by Julian** [comment]
Yes, any nested amount of errors in `.context` may continue to have `.context` attributes with more sub-errors. Use a while loop, or some loop.

**Comment by beck3905** [comment]
Oh I get that they can have the `.context`.  I think maybe I'm confusing `ErrorTree` and errors themselves.  So I start with an `ErrorTree` and I can iterate that directly by doing `for child_tree in error_tree`, but then an individual `ErrorTree` can have `.errors`.  Then, errors can have `.context` which is a list of more errors.  But I would never iterated directly on an error object right?  I would only iterated on the `error.context` property, correct?

**Comment by Julian** [comment]
Correct! `ErrorTree`s are not particularly related to anything you're doing, they're just a different interface for interacting with errors than just in a flat thing.

**Comment by beck3905** [comment]
So does that mean there is a better way to iterate through all the errors without using `ErrorTree`s?

**Comment by Julian** [comment]
Sure, just don't create one! `errors = validator.iter_errors(...)`, now do whatever you'd like.

**Comment by Julian** [comment]
Hopefully the above helped, if not feel free to open a discussion or pop into the Slack.
