### ISSUE TITLE
jsonschema says that my schema is invalid, other sources disagree

### ISSUE THREAD

**Issue by EricPrescottGagnon** [python-jsonschema/jsonschema#1015]
Hello,

  I have an issue with the following (simplified) schema that was generated by pydantic:

```
{"title": "Person",
 "type": "object",
 "properties": {"pairs": {"title": "Pairs",
   "type": "array",
   "items": {"type": "array",
    "items": [{"title": "First"}, {"title": "Second"}],
    "minItems": 2,
    "maxItems": 2}}}}
```

I am seeing that jsonschema from v4.0.0 to v.4.17.0 returns the following error:

```
jsonschema.exceptions.SchemaError: [{'type': 'string'}, {'type': 'string'}] is not of type 'object', 'boolean'
```

However, v3.2.0 doesn't see a problem with my schema.

To double check I tried one multiple web validators, all telling me my schema is valid. For instance:
https://json-everything.net/json-schema/
https://www.jsonschemavalidator.net/

**Comment by robherring** [comment]
It is validating against 2020-12 where 'items' can only be an object. The array form is handled by prefixItems. In earlier drafts, 'items' could be either an array or object. Adding $schema with the draft you want should fix it.

**Comment by EricPrescottGagnon** [comment]
Thanks! That worked!
