### ISSUE TITLE
Are PRs that add typing to the code appreciated?

### ISSUE THREAD

**Issue by DanielNoord** [python-jsonschema/jsonschema#1017]
Basically the issue title: are such PRs welcomed? The `stubs` in `typeshed` are outdated and instead of updating them there I thought I could also invest some time in the project itself so they are more readily available for everybody.

**Comment by Julian** [comment]
If done incrementally (in small chunks) and in a way that doesn't make the code significantly worse (locally or in aggregate) yes!

@sirosen has some plans there too which may be worth coordinating.

And appreciate both the offer and you asking!

**Comment by Viicos** [comment]
If I can get any free time, I'll be happy to work on adding types on this library. Just wanted to know if there was any rules we should follow? (e.g. are we going for `mypy --strict`? Do we need explicit return types?)

**Comment by Julian** [comment]
Hi there! Definitely agree on my side on the straightforward ones being easiest to get in, so those are definitely welcome!

I have to teach myself what `mypy_primer` is -- honestly my experience getting `referencing` written with types led me to basically ditch mypy and switch to using `pyright` which had some better defaults IMHO -- but indeed I think there's likely plenty of low hanging fruit we can get to here!
