### ISSUE TITLE
Pattern property `^.+$` works with empty strings.

### ISSUE THREAD

**Issue by erikhuck** [python-jsonschema/jsonschema#1024]
The regular expression `^.+$` indicates *one* or more characters where an empty string has 0. However, consider the following schema:
```
{
    'type': 'object',
    'minProperties': 1,
    'patternProperties': {
        '^.+$': {
            'type': 'array',
            'minItems': 1,
            'items': {
                'type': 'string',
                'minLength': 1
            }
        }
    }
}
```

Using this schema with `jsonschema.validate()` and this dictionary: `{'': ['a']}` will pass. But emtpy strings for property names should not be allowed with the given regular expression for the patternProperties.

**Comment by Julian** [comment]
I'm not sure I follow why you expect it to fall. As you say, empty strings don't match the pattern (though even if it did, it seems like visually that the value should match).

**Comment by erikhuck** [comment]
@Julian Yes empty strings do not match the pattern. So why does the object `{'': ['a']}` pass? The property name is an empty string. So it should fail because it does not match the `propertyNames` regular expression.

**Comment by erikhuck** [comment]
Using this [tester app](https://www.regextester.com/106204), we see that `^.*$` gets a match for an empty string. As it should because `*` indicates 0 or more. But `^.+$` gets no matches for an empty string. And it shouldn't because `+` requires at least one character. See in the screenshots how it says "1 match" for `^.*$` but "no match" for `^.+$`. Empty strings should not match `^.+$`.
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/42946548/205457576-6dea7f49-9f65-4f7f-baf7-96d23726bad1.png">
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/42946548/205457588-218a82e4-97af-4c29-816d-cd1ebb0818a1.png">

**Comment by Julian** [comment]
`propertyNames` means "if a property matches, it must validate under this schema". It has nothing to do with properties which don't match.

**Comment by erikhuck** [comment]
@Julian How do I get the properties that don't match to fail?

**Comment by Julian** [comment]
Depends what you mean by that, if you want all properties that don't match to be disallowed you might be asking about `additionalProperties: false`.

**Comment by erikhuck** [comment]
@Julian That worked. Thank you for your help!
