### ISSUE TITLE
如果有多个异常，只会抛出最后一个异常

### ISSUE THREAD

**Issue by dch-21** [python-jsonschema/jsonschema#1029]
from jsonschema import validate, draft7_format_checker
from jsonschema.exceptions import SchemaError, ValidationError
from jsonschema.validators import validator_for

my_schema = {
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "TestInfo",
    "description": "some information about test",
    "type": "object",
    "properties": {
        "name": {
            "description": "Name of the test"
            ,"type": "object"
            ,"properties": {
                "str":{
                    "description": "Name of the test",
                    "type": "string"
                }
            }
            ,"required":['str']
        },
        "age": {
            "description": "age of test",
            "type": "integer",
            "minimum": 0,
            "maximum": 120
        },
        "pet": {
            "enum": ["dog", "cat"]
        }
    },
    "required": [
        "name", "age", "pet"
    ]
}

json_data1 = {
    "name": {"str":'bbbbb'},
    "age": 25,
    "pet": "cat"
}

json_data2 = {
    "name": {"str1":'bbbbb'},
    "age": 25,
    "pet": "cat"
}

json_data3 = {
    "name": {"str":'bbbbb'},
    "age": 25,
    "pet": "cat1"
}

json_data4 = {
    "name": {"str":'bbbbb'},
    "age": -1,
    "pet": "cat"
}

json_data5 = {
    "name": {"str": 1},
    "age": 120,
    "pet": "cat1"
}

def json_check(data,schema):
    try:
        validate(instance=data, schema=schema, format_checker=draft7_format_checker)
    except SchemaError as e:
        return 1, "验证模式schema出错，出错位置：{}，提示信息：{}".format(" --> ".join([i for i in e.path if i]), e.message)
    except ValidationError as e:
        return 2,"不符合schema规定，出错字段：{}，提示信息：{}".format(" --> ".join([i for i in e.path if i]), e.message)
    else:
        return 0,'success'

def json_check_by_validator_for(data, schema):
    error = ""
    try:
        validate(instance=data, schema=schema, format_checker=draft7_format_checker)
    except(SchemaError, ValidationError) as e:
        if type(e) == SchemaError:
            error += "验证模式schema出错，出错位置：{}，提示信息：{}".format(" --> ".join([i for i in e.path if i]), e.message)
        elif type(e) == ValidationError:
            error += "验证模式schema出错，出错位置：{}，提示信息：{}".format(" --> ".join([i for i in e.path if i]), e.message)
    else:
        return 0,'success'
    return 1,error

print(json_check(json_data1,my_schema))

print(json_check(json_data2,my_schema))

print(json_check(json_data3,my_schema))

print(json_check(json_data4,my_schema))

print(json_check(json_data5,my_schema))

print(json_check_by_validator_for(json_data5,my_schema))

**Comment by dch-21** [comment]
for json_data5 ,  The str is one of properties of name, str is defined as string， but I assignment it as int . It conflicts with the definition. The pet is another of properties of name, pet is defined as enmu, but cat1 is not one of ['dog', 'cat']. The result is show the pet error not show str error

**Comment by Julian** [comment]
I see -- the code you pasted isn't runnable, but I guess from what I see that you're using `validate`. That raises one exception. If you want all errors, you want [`iter_errors`](https://python-jsonschema.readthedocs.io/en/stable/api/jsonschema/#jsonschema.Validator.iter_errors).

**Comment by dch-21** [comment]
Thanks， I will try it
