### ISSUE TITLE
Move 'attrs' package to [project.optional-dependencies]

### ISSUE THREAD

**Issue by swaldhoer** [python-jsonschema/jsonschema#1051]
The 'attrs' package seems only to be used for testing (see [here](https://github.com/python-jsonschema/jsonschema/search?q=attrs)).
Removing an install-dependency is always good (package less likey to break etc.).
Therefore I think it should be moved from *[project] dependencies* to *[project.optional-dependencies]*.

**Comment by Julian** [comment]
Hi there. Thanks for the issue. Attrs is used throughout the package, not just in tests. Its import name also includes `attr`.
