### ISSUE TITLE
Docs: Example importing json schema from file

### ISSUE THREAD

**Issue by LecrisUT** [python-jsonschema/jsonschema#1054]
It is not obvious how one should be importing a json schema from a local file, e.g.:
```
--- root
 |-- schema
   |-- schema_root.json
   |-- schema_other.json
```

where `schema_root.json` refers to `schema_other.json`, e.g.:
```json
{
  "$id": "resource:/schema/schema_root.json",
  "$schema": "http://json-schema.org/draft-07/schema",
  "properties": {
    "other": {
      "$ref": "schema_other.json"
    }
}
```

Is it sufficient to just `json.load()`? How does it know the `BaseRef` and if it's loaded as a file or an URL?

**Comment by Julian** [comment]
Hi there! This is changing alongside #1049 which should be merged any day now (and then in a beta release).

Specifically it should be documented here: https://python-jsonschema--1049.org.readthedocs.build/en/1049/referencing/#making-additional-in-memory-schemas-available

Have a look and feel free to follow up if you still feel more documentation is needed for it!

**Comment by Julian** [comment]
(Note that so long as that branch isn't merged yet if you want to try it out you'll have to install from the branch of course.)
