### ISSUE TITLE
Couldn't find a setup script in /tmp/easy_install-3usjdbcc/rpds_py-0.6.1.tar.gz

### ISSUE THREAD

**Issue by Christian-B** [python-jsonschema/jsonschema#1058]
Our github actions tried to easyinstall the 4.18.0a1 release

Searching for jsonschema
Reading https://pypi.org/simple/jsonschema/
Downloading https://files.pythonhosted.org/packages/81/b6/22bc5763f3ee849e13f64ba0d67c3dafdff8f426ff22c4abe551ebc4a9e6/jsonschema-4.18.0a1-py3-none-any.whl#sha256=29c0a6a25c80e6cee56bc87c97a6d67f798cf959401b5408861fe89034b250cd
Best match: jsonschema 4.18.0a1
Processing jsonschema-4.18.0a1-py3-none-any.whl
Installing jsonschema-4.18.0a1-py3-none-any.whl to /opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages
Adding jsonschema 4.18.0a1 to easy-install.pth file
Installing jsonschema script to /opt/hostedtoolcache/Python/3.7.16/x64/bin

Installed /opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/jsonschema-4.18.0a1-py3.7.egg
Searching for rpds-py>=0.6.1
Reading https://pypi.org/simple/rpds-py/
Downloading https://files.pythonhosted.org/packages/63/dd/e75b7c1fff91393990bff8c43fd9d2df18dfc9095626776d8165b4fc67b0/rpds_py-0.6.1.tar.gz#sha256=dad0e599f6e010e25e1dafeb6bbb6b6bc9f8a8b60435da68b5f343ce2ec25d7d
Best match: rpds-py 0.6.1
Processing rpds_py-0.6.1.tar.gz
error: Couldn't find a setup script in /tmp/easy_install-3usjdbcc/rpds_py-0.6.1.tar.gz

yes I know we should not use an alpha release but I have not worked out how to stop easy install doing that.

**Comment by Christian-B** [comment]
Thank you for the quick reply.

My actual issue was not easy_install but he trying to do a pip install of 4.18.0a1 on python 3.7

Both jsonschema 4.18.0a1 and rpds_py-0.6.1 are marked as
"Requires: Python >=3.8"

So this was rightfully closed.

Sorry for the confusion.

**Comment by Julian** [comment]
Ah, huh, interesting -- did you try to directly install that version? Otherwise pip should not have picked up that version if you were on 3.7 (at least any pip newer than version 8, which is quite old)

Thanks for the detail though hope it helps if anyone else runs into this.
