### ISSUE TITLE
pyrsistent 0.14.0 does not support Python 3.10

### ISSUE THREAD

**Issue by andy-maier** [python-jsonschema/jsonschema#1071]
The latest released jsonschema version (4.17.3) requires pyrsistent>=0.14.0, but pyrsistent 0.14.0 still imports Mapping from collections, which was removed in Python 3.10.

The change log of pyrsistent says that version 0.18.1 added support for Python 3.10. I verified that pyrsistent 0.15.0 imports Mapping and other ABC types now from collections.abc, but it seems the official support is in 0.18.1.

pyrsistent 0.18.1 requires Python>=3.7.

I saw that pyrsistent is no longer used in the master branch of jsonschema, so I'm not sure whether you will release a new update of 4.17.x, but I wanted to report it in any case.

We have circumvented the issue by requiring pyrsistent>=0.18.1 on Python>=3.10 in our projects that use jsonschema.

**Comment by Julian** [comment]
Thanks, indeed the next version of jsonschema won't have it as a dependency. Appreciate the report though!
