### ISSUE TITLE
It seems to be impossible for me to use relative references more than one layer deep

### ISSUE THREAD

**Issue by willjhenry** [python-jsonschema/jsonschema#1092]
I have the following file structure:

- JSON_schemas/
 - forms/
   - form_templates.json
   - form_templates_versions.json
   - form_templates_versions_categories.json

form_templates.json:
```
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "id": { "type": "integer" },
        "type": { "type": "string", "enum": ["survey"] },
        "created_datetime": { "type": "string", "format": "date-time" },
        "created_by": { "type": "string" },
        "creator_role": { "type": ["string", "null"] },
        "active": { "type": "boolean" },
        "versions": {
            "type": "array",
            "items": {
                "$ref": "file:JSON_schemas/forms/form_templates_versions.json"
            }
        }
    },
    "patternProperties": {
        "^_": { "type": "string" }
    },
    "additionalProperties": false
}
```

form_templates_versions.json:
```
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "id": { "type": "integer" },
        "title": { "type": ["string", "null"] },
        "description": { "type": ["string", "null"] },
        "published": { "type": "boolean" },
        "days_to_complete": { "type": "integer" },
        "survey_intro": { "type": ["string", "null"] },
        "categories": {
            "type": "array",
            "items": {
                "$ref": "file:JSON_schemas/forms/form_templates_versions_categories.json"
            }
        }
    },
    "patternProperties": {
        "^_": { "type": "string" }
    },
    "additionalProperties": false
}
```

form_templates_versions_categories.json:
```
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "id": { "type": "integer" },
        "order": { "type": "integer" },
    },
    "required": ["order", "hidden", "title", "description", "contents"],
    "patternProperties": {
        "^_": { "type": "string" }
    },
    "additionalProperties": false
}
```

When loading the form_templates.json schema, the ref to "file:JSON_schemas/forms/form_templates_versions.json" correctly resolves, but then the ref to "file:JSON_schemas/forms/form_templates_versions_categories.json", inside of form_templates_versions.json does not resolve, it ends up looking for an absolute path "JSON_schemas/forms/JSON_schemas/forms/form_templates_versions_categories.json"

I have tried different formats for the file URI, and I have tried using $id. It seems the urljoin, that is used in the validator returns an absolute path in all cases.

**Comment by Julian** [comment]
Hi there -- a lot of this has changed now with the new `$ref` support, available in the prerelease which you can install via `pip install --pre jsonschema`.

You likely should give that a shot, the docs for doing this should be [here](https://python-jsonschema.readthedocs.io/en/latest/referencing/#resolving-references-from-the-file-system) though feel free to ask if they're insufficient.
