### ISSUE TITLE
TypeError: joinpath() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by devRoemer** [python-jsonschema/jsonschema#1096]
With 4.17.3 i am getting the below exception. Version 4.17.0 works just fine. (Python 3.8)

I figured out that it is related to the changes of this commit:
https://github.com/python-jsonschema/jsonschema/commit/4f8f346cc475439715833ac6bd6e5c5e3dc21ee3

Sample data and sample schema:
[test_data.txt](https://github.com/python-jsonschema/jsonschema/files/11381836/test_data.txt)

The json was loaded by json.load(file). The schema was defined as dictionary variable.
Then validate is called like that: validate(instance=json_instance, schema=schema)

Exception:

    app/services/validation_service.py:88: in _validate_json_schema
        validate(instance=json_instance, schema=schema)
    /home/vscode/.local/lib/python3.8/site-packages/jsonschema/validators.py:1117: in validate
        cls.check_schema(schema)
    /home/vscode/.local/lib/python3.8/site-packages/jsonschema/validators.py:226: in check_schema
        validator = Validator(
    <attrs generated init jsonschema.validators.create.<locals>.Validator>:5: in __init__
        self.__attrs_post_init__()
    /home/vscode/.local/lib/python3.8/site-packages/jsonschema/validators.py:216: in __attrs_post_init__
        self.resolver = RefResolver.from_schema(
    /home/vscode/.local/lib/python3.8/site-packages/jsonschema/validators.py:772: in from_schema
        return cls(base_uri=id_of(schema), referrer=schema, *args, **kwargs)  # noqa: B026, E501
    /home/vscode/.local/lib/python3.8/site-packages/jsonschema/validators.py:744: in __init__
        self.store = _utils.URIDict(_store_schema_list())

    def _store_schema_list():
        if not _VOCABULARIES:
            package = _utils.resources.files(__package__)
           for version in package.joinpath("schemas", "vocabularies").iterdir():
           TypeError: joinpath() takes 2 positional arguments but 3 were given

**Comment by Julian** [comment]
Hi, please include a full traceback, what you shared looks mangled.

And where did you get this installation of Python? joinpath takes [multiple arguments even on 3.8](https://docs.python.org/3.8/library/pathlib.html#pathlib.PurePath.joinpath) so something sounds suspicious about the installation.

**Comment by Julian** [comment]
Happy to look at this if you have some more info!
