### ISSUE TITLE
Filesystem replication system breaks internal schema loader function

### ISSUE THREAD

**Issue by dylan-robins** [python-jsonschema/jsonschema#1098]
Hi, thanks for the great work on this project. I'm attempting to use it in an industrial setting where the entire filesystem (incl. virtualenvs) is replicated across server clusters in various countries using Synchronicity, which tends to pollute directories by placing `.SYNC` folders at every level.

However this breaks the `_store_schema_list()` function in `validators.py`. I cannot find this function in the source code, however it is present in the python files installed by pip. It recursively loads all json vocabulary files in `__package__/schemas/vocabularies`, but if Synchronicity places a .SYNC folder there it crashes. Here is the function:

```py
def _store_schema_list():
    if not _VOCABULARIES:
        package = _utils.resources.files(__package__)
        for version in package.joinpath("schemas", "vocabularies").iterdir():
            # PROPOSAL: ADD FILTER HERE
            for path in version.iterdir():
                # PROPOSAL: ADD ANOTHER FILTER HERE
                if not path.is_file():
                    continue
                vocabulary = json.loads(path.read_text())
                _VOCABULARIES.append((vocabulary["$id"], /vocabulary))
    return [
        (id, validator.META_SCHEMA) for id, validator in _META_SCHEMAS.items()
    ] + _VOCABULARIES
```

I'd suggest adding some sort of filter to this function in the two places I've listed, or using a glob pattern of some description to only load what you expect to be located there.

I have temporarily patched the function to work on our system by adding the following check, however this is obviously a dirty hack and should be replaces with something more robust
```py
            if version.name == ".SYNC":
                continue
```

Not sure how this function is being created as it is seemingly not in the sources, I'll have a look in more detail at a later date. Any thoughts on this?

**Comment by Julian** [comment]
Hi there -- this functionality has changed for the upcoming 4.18 release which is probably why you're not seeing it on `main`, it's not there anymore.

Feel free to try out the alpha and see if it fixes your issue (it may). I'm not sure I'm interested in thinking too hard about this case if not honestly, as you probably should consider telling your syncer not to create files in random places, but I'm open to hearing feedback.
