### ISSUE TITLE
multipleOf throwing ValidationError for specific number

### ISSUE THREAD

**Issue by vigneshkv23** [python-jsonschema/jsonschema#1099]
This is a strange issue. I have created a simple JSON schema to validate float which can be a maximum of two digits.

 `schema = {'type': 'number', 'multipleOf': 0.01}`
`jsonschema.validate(1.11, schema)`

> =>jsonschema.validate(1.11, schema)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python38\lib\site-packages\jsonschema\validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: 1.11 is not a multiple of 0.01

Observations-

1. From 1.11 till 1.19 throwing the validation error but from 1.21 No errors work as expected.
2. Again from 10.11 till 10.21 throwing the validation error but from 10.22 No errors work as expected.
3. 2.11 , 2.13 throwing the validation error 
4. But the other number works fine.

**Comment by Julian** [comment]
Hi there -- this is expected behavior, see e.g. [some of the previous issues linked here](https://github.com/python-jsonschema/jsonschema/issues/810#issuecomment-961748247).

Essentially, if you don't want float division, use `decimal.Decimal` when you deserialize your JSON.
