### ISSUE TITLE
EncodingWarning issued when PYTHONWARNDEFAULTENCODING=true

### ISSUE THREAD

**Issue by jaraco** [python-jsonschema/jsonschema#1107]
When enabling PYTHONWARNDEFAULTENCODING, it triggers a warning in jsonschema (per [PEP 597](https://peps.python.org/pep-0597/)).

```
tests/test_scripts.py::TestNotebookDepsReader::test_one_code_block
  /Users/jaraco/code/jaraco/pip-run/.tox/py/lib/python3.11/site-packages/jsonschema/validators.py:109: EncodingWarning: 'encoding' argument not specified
    vocabulary = json.loads(path.read_text())

```

Probably that needs to be `path.read_text(encoding='utf-8')`.

**Comment by Julian** [comment]
Thanks! Fixed (in another repo, as this code has moved for the next release which is already in beta.)

Appreciated.
