### ISSUE TITLE
Regex pattern doesn't seem to be performing as expected?

### ISSUE THREAD

**Issue by YaoJusheng** [python-jsonschema/jsonschema#1110]
when validating the jsonschema with `validate`, it was found that the pattern did not execute successfully as expected, and the usage as follows:
```python
from jsonschema import validate

run={
    "type": "object",
    "properties": {
        "version": {
            "default": "v1.0",
            "type": "string",
            "pattern": "^(v(\\d\\.){1,2}\\d)$",
        },
    }, 
    "additionalProperties": False
}

test_data={'version': 'v1.11.1'}

validate(test_data, run)
```

An error is reported directly after execution: 
```
jsonschema.exceptions.ValidationError: 'v1.11.1' does not match '^(v(\\d\\.){1,2}\\d)$'
```

The version of `jsonschema` is `4.17.3`, and the version of `python` is `3.8.10`.

**Comment by Julian** [comment]
As the message says, your value doesn't match your pattern:

```
re.compile("^v(\\d\\.)\\{1,2\\}\\d$").search("v1.11.1") is None
True
```

Presumably you're missing a repetition operator, as your `11` is multiple digits.
