### ISSUE TITLE
4.18.0: sphinx warnings `reference target not found`

### ISSUE THREAD

**Issue by kloczek** [python-jsonschema/jsonschema#1113]
On building my packages I'm using `sphinx-build` command with `-n` switch which shows warmings about missing references. These are not critical issues.
Here is the output with warnings:

<details>

```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v6.2.1
Initializing Spelling Checker 8.0.0
making output directory... done
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://referencing.readthedocs.io/en/stable/objects.inv...
loading intersphinx inventory from https://json-schema.org/understanding-json-schema/objects.inv...
building [mo]: targets for 0 po files that are out of date
writing output...
building [man]: all manpages
updating environment: [new config] 10 added, 0 changed, 0 removed
reading sources... [100%] validate
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-jsonschema.3 { validate errors referencing creating faq api/index api/jsonschema/validators/index api/jsonschema/exceptions/index api/jsonschema/protocols/index } /home/tkloczko/rpmbuild/BUILD/jsonschema-4.18.0/jsonschema/validators.py:docstring of referencing.jsonschema._dollar_id:1: WARNING: py:class reference target not found: Schema
/home/tkloczko/rpmbuild/BUILD/jsonschema-4.18.0/jsonschema/validators.py:docstring of referencing.jsonschema._dollar_id:1: WARNING: py:class reference target not found: URI
/home/tkloczko/rpmbuild/BUILD/jsonschema-4.18.0/jsonschema/validators.py:docstring of referencing.jsonschema._dollar_id:1: WARNING: py:class reference target not found: Schema
/home/tkloczko/rpmbuild/BUILD/jsonschema-4.18.0/jsonschema/validators.py:docstring of referencing.jsonschema._dollar_id:1: WARNING: py:class reference target not found: URI
/home/tkloczko/rpmbuild/BUILD/jsonschema-4.18.0/jsonschema/validators.py:docstring of referencing.jsonschema._legacy_id:1: WARNING: py:class reference target not found: ObjectSchema
/home/tkloczko/rpmbuild/BUILD/jsonschema-4.18.0/jsonschema/validators.py:docstring of referencing.jsonschema._legacy_id:1: WARNING: py:class reference target not found: URI
/home/tkloczko/rpmbuild/BUILD/jsonschema-4.18.0/jsonschema/validators.py:docstring of referencing.jsonschema._legacy_id:1: WARNING: py:class reference target not found: ObjectSchema
/home/tkloczko/rpmbuild/BUILD/jsonschema-4.18.0/jsonschema/validators.py:docstring of referencing.jsonschema._legacy_id:1: WARNING: py:class reference target not found: URI
/home/tkloczko/rpmbuild/BUILD/jsonschema-4.18.0/jsonschema/validators.py:docstring of referencing.jsonschema._legacy_dollar_id:1: WARNING: py:class reference target not found: Schema
/home/tkloczko/rpmbuild/BUILD/jsonschema-4.18.0/jsonschema/validators.py:docstring of referencing.jsonschema._legacy_dollar_id:1: WARNING: py:class reference target not found: URI
/home/tkloczko/rpmbuild/BUILD/jsonschema-4.18.0/jsonschema/validators.py:docstring of referencing.jsonschema._legacy_dollar_id:1: WARNING: py:class reference target not found: Schema
/home/tkloczko/rpmbuild/BUILD/jsonschema-4.18.0/jsonschema/validators.py:docstring of referencing.jsonschema._legacy_dollar_id:1: WARNING: py:class reference target not found: URI
done
build succeeded, 12 warnings.
```
</details>

You can peak on fixes that kind of issues in other projects
https://github.com/RDFLib/rdflib-sqlalchemy/issues/95
https://github.com/RDFLib/rdflib/pull/2036
https://github.com/click-contrib/sphinx-click/commit/abc31069
https://github.com/frostming/unearth/issues/14
https://github.com/jaraco/cssutils/issues/21
https://github.com/latchset/jwcrypto/pull/289
https://github.com/latchset/jwcrypto/pull/289
https://github.com/pypa/distlib/commit/98b9b89f
https://github.com/pywbem/pywbem/pull/2895
https://github.com/sissaschool/elementpath/commit/bf869d9e
https://github.com/sissaschool/xmlschema/commit/42ea98f2
https://github.com/sqlalchemy/sqlalchemy/commit/5e88e6e8

**Comment by Julian** [comment]
The [CI build](https://github.com/python-jsonschema/jsonschema/blob/main/noxfile.py#L158) builds with not only `-n` but also `-W` and has no such issue. Feel free to minimize if there indeed is one, and to do so in a way that uses the supported ways to build, otherwise as usual, I've warned you about filing issues that are specific to your crazy build setups.

**Comment by kloczek** [comment]
Please try to have look on https://python-jsonschema.readthedocs.io/en/stable/ and check do you see not only highlights but links in those places where are printed warnings.
As I'm interested only roff output (man page) I'm noit affected by those warnings but .html, .pdf and .qch rendered outputs are ..

**Comment by Julian** [comment]
Again. There are no warnings printed in the builds done neither here in CI nor in ReadTheDocs.

**Comment by kloczek** [comment]
Looking on https://github.com/python-jsonschema/jsonschema/actions/runs/5471296205/jobs/9962297372 it is not possible to find out which one version of the python and sphinx is used in CI because sphinx is executed with -q option.
May I ask about version python and sphinx is used in CI? 🤔

**Comment by Julian** [comment]
https://github.com/python-jsonschema/jsonschema/blob/7046da13cf41fcfa355fcd68097e75fa03c1f0fc/.readthedocs.yaml#L8
https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#using-the-python-version-input
https://github.com/python-jsonschema/jsonschema/blob/7046da13cf41fcfa355fcd68097e75fa03c1f0fc/.github/workflows/ci.yml#L83-L84
