### ISSUE TITLE
Requirement for rust and cargo?

### ISSUE THREAD

**Issue by oc-ben-ellis** [python-jsonschema/jsonschema#1114]
Is it intentional that there is now a requirement for rust and cargo to be installed? This has broken the poetry project which can now not be installed without rust and cargo. I've raised a ticket separately with them (https://github.com/python-poetry/poetry/issues/8160) as suspect they'll lock into the previous versions of jsonschema.

Running the below gives an error,

`docker run -it --rm alpine:latest /bin/sh -c "apk add python3 py3-pip && pip install jsonschema"

```
Collecting rpds-py>=0.7.1 (from jsonschema)
  Downloading rpds_py-0.8.4.tar.gz (15 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]

      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

      Checking for Rust toolchain....
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
```

Workaround is to install rust and cargo,

`docker run -it --rm alpine:latest /bin/sh -c "apk add rust cargo python3 py3-pip && pip install jsonschema"`

This works.

**Comment by Julian** [comment]
There's a (indeed intentional) dependency on rust for *building* from source, and no current MUSL wheels yet. The latter is tracked at crate-py/rpds#6 and just requires some understanding of what to tweak in maturin which hasn't been figured out yet. Help certainly welcome.
