### ISSUE TITLE
extend() doesn't copy applicable_validators

### ISSUE THREAD

**Issue by PetrusAsikainen** [python-jsonschema/jsonschema#1125]
It seems the `applicable_validators` property from c6b0fc454d9c3d5c3f2f27c8dc851cd9691ec9ff never made it to [`extend`](https://github.com/python-jsonschema/jsonschema/blob/main/jsonschema/validators.py#L493).

This means that `extend`ing `Draft4Validator` (or other legacy validators) makes it consider properties next to `$ref` again. (This made `connexion` break OpenAPI 3.0 spec - spec-first/connexion#1721)

### Steps to reproduce

```python
import jsonschema

schema = {
  "$defs": { "test": { "type": "number" } },
  "$ref": "#/$defs/test",
  "maximum": 1
}

# no error, maximum is ignored as per spec
jsonschema.validate(schema=schema, instance=2, cls=jsonschema.Draft4Validator)

# extend() with no changes
BadValidator = jsonschema.validators.extend(jsonschema.Draft4Validator)

# jsonschema.exceptions.ValidationError: 2 is greater than the maximum of 1
jsonschema.validate(schema=schema, instance=2, cls=BadValidator)
```

### Environment

```
$ python --version
Python 3.11.2
$ pip show jsonschema | grep Version
Version: 4.18.2
```

**Comment by Julian** [comment]
Should be released in just a bit in v4.18.3. Thanks.
