### ISSUE TITLE
Properly handle nullable: true from API specification

### ISSUE THREAD

**Issue by gilder48** [python-jsonschema/jsonschema#1128]
We use open api 3.0 and our spec documents have properties that look like the following. 
"Property": {
"type": "boolean",
 "nullable": true
 }
In this instance, the validator will fail if a null value is given, even though nullable is true. 

The current workaround is to manually update the api spec to 
"Property": {
"type": ["boolean", "null"],
 "nullable": true
 }
This would need to be done for all properties being verified. I would request the first scenario being handled without error.

**Comment by Julian** [comment]
This library implements the JSON Schema specifications -- nullable is an OpenAPI concept.
