### ISSUE TITLE
4.18.1 regresses validation for titiler and pystac

### ISSUE THREAD

**Issue by philvarner** [python-jsonschema/jsonschema#1130]
This is a regression as of 4.18.1.

This is causing the issue reported here: https://github.com/developmentseed/titiler/issues/667 and the fix in pystac https://github.com/stac-utils/pystac/pull/1189

The immediate error is:

```
            except (TypeError, LookupError):
>               raise exceptions._RefResolutionError(
                    f"Unresolvable JSON pointer: {fragment!r}",
                )
E               jsonschema.exceptions._RefResolutionError: Unresolvable JSON pointer: 'definitions/assets'
```

Which is coming from the call to the pystac validate method: `pystac.Item.from_dict(body).validate()`

pystac uses RefResolver in local_validator.py and stac_validator.py classes.

One issue that's caused problems in the past is the use of the Draft 7 schema for STAC `http://json-schema.org/draft-07/schema#`, though this may be unrelated.

Reproduction:

```
git clone git@github.com:stac-utils/pystac.git
cd pystac
pip install -e . 
pip install -e .[test]
pip install jsonschema==4.18.3
pytest 
```

Numerous tests will fail with the exception `jsonschema.exceptions._RefResolutionError: Unresolvable JSON pointer: 'definitions/assets'`

These tests pass if `pip install jsonschema==4.18.0` is installed instead.

**Comment by Julian** [comment]
Hi there, please include code to reproduce the issue being reported.

**Comment by philvarner** [comment]
I just remembered this issue with the alphas, which may be related https://github.com/python-jsonschema/jsonschema/issues/1064#issuecomment-1478404924

**Comment by Julian** [comment]
I see from a browser that you've edited in a link to the pystac test suite -- that's a start, but it's significantly more likely I can look at this if you include a code snippet with no external dependencies that uses this library and which produces the issue you are trying to report.

**Comment by EliahKagan** [comment]
I'm also having what appears to be the same issue, detailed in https://github.com/EliahKagan/pylint-sarif/issues/19. As here:

- It is a `jsonschema.exceptions._RefResolutionError: Unresolvable JSON pointer` message.
- It happens with jsonschema 4.18.1, 4.18.2, and 4.18.3, but not with 4.18.0 (and not with any 4.17.\*).

Unfortunately, I also don't currently have a short and self-contained example of code that causes the problem, and it is happening when jsonschema is used via [python-jsonschema-objects](https://github.com/cwacek/python-jsonschema-objects).

However, in case it helps, the schema in use is https://github.com/EliahKagan/pylint-sarif/blob/b75a08f/sarif-schema.json and [the code that raises the exception](https://github.com/EliahKagan/pylint-sarif/blob/b75a08f/src/pylint2sarif.py#L136-L137) is:

```python
import python_jsonschema_objects as pjs
...
builder = pjs.ObjectBuilder(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'sarif-schema.json'))
self.sarif = builder.build_classes()
```

python-jsonschema-objects [calls into jsonschema](https://github.com/cwacek/python-jsonschema-objects/blob/0.4.2/python_jsonschema_objects/classbuilder.py#L485), as shown in the full traceback in https://github.com/EliahKagan/pylint-sarif/issues/19. The part of that traceback that shows the code that ran in jsonschema is:

```text
  File "/home/ek/.cache/pypoetry/virtualenvs/pylint-sarif-unofficial-4ksIlfgF-py3.11/lib/python3.11/site-packages/jsonschema/validators.py", line 1034, in resolving
    url, resolved = self.resolve(ref)
                    ^^^^^^^^^^^^^^^^^
  File "/home/ek/.cache/pypoetry/virtualenvs/pylint-sarif-unofficial-4ksIlfgF-py3.11/lib/python3.11/site-packages/jsonschema/validators.py", line 1081, in resolve
    return url, self._remote_cache(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ek/.cache/pypoetry/virtualenvs/pylint-sarif-unofficial-4ksIlfgF-py3.11/lib/python3.11/site-packages/jsonschema/validators.py", line 1099, in resolve_from_url
    return self.resolve_fragment(document, fragment)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ek/.cache/pypoetry/virtualenvs/pylint-sarif-unofficial-4ksIlfgF-py3.11/lib/python3.11/site-packages/jsonschema/validators.py", line 1149, in resolve_fragment
    raise exceptions._RefResolutionError(
jsonschema.exceptions._RefResolutionError: Unresolvable JSON pointer: 'definitions/messageClass'
```

I am not assuming this is sufficient information to diagnose the issue, but I'm providing it in the hope that it is more illuminating than distracting. I'd be pleased take any specific requested steps and report back, if that would be of use.

**Comment by Julian** [comment]
Thanks, perhaps close at least, what's an instance / some data that should validate under that schema and produces that error? That'd definitely be the most useful as it'd give us a pair of schema + data reproducing.

Or, given I don't really know anything about python-jsonschema-objects, is that some error it's producing while trying to do whatever schema walking it wants to do -- if so it's going to be less helpful.

**Comment by Julian** [comment]
I'm happy to look at this if someone shares some code which reproduces something here -- for the minute though given there's nothing I can address as-is, going to close. Feel free either to comment or open a new issue as soon as someone has something usable.
