### ISSUE TITLE
pyinstaller hook not working for jsonschema

### ISSUE THREAD

**Issue by Reaster0** [python-jsonschema/jsonschema#1136]
hey all, i tried to build my app using pyinstaller but if i use your library and build, it work,
then i launch the executable and i get : 
```
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEI3cIQcM/jsonschema_specifications/schemas'
```

from what i've seen, it seems that the hook for pyinstaller are broken and it dosen't package the lib when building the app,
do you have any ideas how to fix it?

**Comment by Julian** [comment]
Hi there! Please file this downstream with `pyinstaller` if you don't already find an issue (one may exist as I believe this isn't the first mention of some issue) -- but it's there that whatever bundling related trick is failing to find the data files.
