### ISSUE TITLE
error installing pyyaml 5.4.1

### ISSUE THREAD

**Issue by yangcao77** [python-jsonschema/jsonschema#1139]
same issue as : https://github.com/yaml/pyyaml/issues/724

please bump up `PyYAML==6.0.1` to fix the cython 3 issue

**Comment by Julian** [comment]
Hi there, not sure what repo you meant to file this on but there's no dependency on PyYAML here.

**Comment by feloy** [comment]
@Julian Are you sure? I can see the dependency displayed in this file: docs/requirements.txt

**Comment by Julian** [comment]
Those are the requirements for building this package's documentation, that's not user facing.
