### ISSUE TITLE
Feature request: RefResolver/referencing

### ISSUE THREAD

**Issue by tschmidtb51** [python-jsonschema/jsonschema#1153]
Hi @Julian, I just found a the deprecation warning in our CI/CD log:
```
DeprecationWarning: jsonschema.RefResolver is deprecated as of v4.18.0, in favor of the https://github.com/python-jsonschema/referencing library, which provides more compliant referencing behavior as well as more flexible APIs for customization. A future release will remove RefResolver. Please file a feature request (on referencing) if you are missing an API for the kind of customization you need.
```

Honestly, I haven't fully understood the warning but at least I wanted to raise my hand that we are using this to resolve parts of the [CSAF schema](https://docs.oasis-open.org/csaf/csaf/v2.0/os/schemas/csaf_json_schema.json) in our validation process.

Could you please clarify: Do we need to change to a different library or will https://github.com/python-jsonschema/referencing be able to create a resolver that we can pass towards the draft validator?

Flagging @sthagen for attention

**Comment by Julian** [comment]
Hi there! That message is saying that eventually `RefResolver` will be removed.

It should be reasonably straightforward to move to using a referencing registry, but precisely how might depend on what you're doing with RefResolver.

Definitely happy to answer questions though.

**Comment by tschmidtb51** [comment]
Thank you for your support. The [excellent documentation](https://python-jsonschema.readthedocs.io/en/stable/referencing/) and especially the [migration part](https://python-jsonschema.readthedocs.io/en/stable/referencing/#migrating-from-refresolver) helped to resolve the issue.

**Comment by Julian** [comment]
Glad to hear it!
