### ISSUE TITLE
Contrary to the documentation, a JSON-Schema is not validated against the meta-schema

### ISSUE THREAD

**Issue by exhuma** [python-jsonschema/jsonschema#1155]
Maybe this is a misunderstanding on my part, but [the docs of version 4.19](https://python-jsonschema.readthedocs.io/en/v4.19.0/validate/#the-basics) state the following:

> [validate()](https://python-jsonschema.readthedocs.io/en/stable/api/jsonschema/validators/#jsonschema.validators.validate) will first verify that the provided schema is itself valid, since not doing so can lead to less obvious error messages and fail in less obvious or consistent ways.

I have the following schema:

```json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "data": {
            "type": "array",
            "items:": {"type": "string"},
        },
    },
}
```

Note that this has an incorrect `:` in the "items" key of the array spec.

Given the docs above, I would expect the following code to raise an error about the incorrect schema:

```python
from jsonschema import validate

schema = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "data": {
            "type": "array",
            "items:": {"type": "string"},
        },
    },
}

print(validate({"data": [1, 2, 3]}, schema))
```

What's even worse, the data that I pass for validation has an array of integers and not strings. This has led to surprising bugs in our environment and it took a while to spot the stray character in the schema.

**Comment by Julian** [comment]
The docs are correct, that schema is indeed validated under the metaschema, and the metaschema (and the JSON Schema specification) allows additional properties, so there's nothing invalid about that schema, despite it not doing what you expected unfortunately.

Schemas are not replacements for unit tests, they're just helpful ways to implement validation, so you need to catch this by having unit tests with data you expect to be valid and invalid.
