### ISSUE TITLE
Failed to validate the schema when shifted from RefResolver to Registry 

### ISSUE THREAD

**Issue by vishalmane9** [python-jsonschema/jsonschema#1174]
Description:  Failed to validate the schema when shifted from RefResolver to Registry  and getting an issue of `jsonschema.exceptions._WrappedReferencingError: Unresolvable: file:./dynamic_lists_schema.json#/definitions/dynamic_lists_settings
`

Please refer below files, both are on same levels in directory, This is the test_schema.json
```
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "description": "schema for the JSON settings",
    "type": "object",
    "required": [
        "dynamic_lists"
    ],
    "properties": {
        "dynamic_lists": {
            "$ref": "file:./dynamic_lists_schema.json#/definitions/dynamic_lists_settings"
        }
    }
}
```

and there is another file of dynamic_lists_schema.json, using this file in test_schema.json
```

{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "definitions": {
        "dynamic_lists_settings": {
            "type": "object",
            "description": "Dynamic block list feature",
            "additionalProperties": false,
            "properties": {
                "enabled": {
                    "type": "boolean",
                    "description": "enables or disables the entire dynamic blocklist feature"
                },
                "configurations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dynamic_lists_configuration"
                    }
                }
            }
        },
        "dynamic_lists_configuration": {
            "type": "object",
            "description": "Dynamic block list configurations",
            "additionalProperties": false,
            "properties": {
                "enabled": {
                    "type": "boolean",
                    "description": "True, if user want this configuration to be active."
                },
                "name": {
                    "type": "string",
                    "description": "Name of the block list from source"
                },
                "id": {
                    "type": "string",
                    "description": "ID of the block list from source"
                },
            }
    }
}
```

**Comment by Julian** [comment]
That isn't a valid URI -- relative file URIs don't exist in that way. Please look around for other similar issues both here and in the referencing repo, and follow up if you still have questions.

**Comment by vishalmane9** [comment]
I didn't find something to provide the relative path of the schema file in $ref, can you please let me know if you have any idea about it...it will be really helpful

**Comment by Julian** [comment]
https://referencing.readthedocs.io/en/stable/intro/#populating-registries is essentially the basic documentation and seems like it should work for your case -- give both your schemas IDs, populate a registry with both, and then you can use those IDs within the schemas to refer to one or the other.

**Comment by vishalmane9** [comment]
Thanks for the reply...I have gone through the Document you provided but didn't find any example, for populating the IDs, can you please provide some link or document which shows how to IDs in schemas
