### ISSUE TITLE
Issue with oneOf validation

### ISSUE THREAD

**Issue by lbpelegrini** [python-jsonschema/jsonschema#1194]
I have the following schema and value:

Schema:
`
{
	"type":"object",
	"required":["my_date"],
	"properties":{
		"my_date":{
			"title":"My date",
			"type":"array",
			"minItems":1,
			"items":{
				"type":"object",
				"required":["value"],
				"properties":{
					"value":{
						"title":"My date",
						"type":"string",
						"oneOf":[
							{
								"type":"string",
								"format":"date"
							},
							{
								"type":"string",
								"format":"date-time"
							}
						]
					}
				}
			}
		}
	}
}
`

Json:
`
{
	"my_date":[
		{
			"value": "2021-01-01"
		}
	]
}
`

Error: "'2021-01-01' is valid under each of {'type': 'string', 'format': 'date-time'}, {'type': 'string', 'format': 'date'}"

It looks like there's something wrong with the oneOf condition, since I ran some tests removing the format checkers, or making the formats equal (using "date" in both) and it always result in error when using more than one condition in oneOf.

I don't know if that's the expected behaviour, but a test with www.jsonschemavalidator.net resulted no errors.

Version: 4.20.0

**Comment by Julian** [comment]
Please include what code you are running.

**Comment by lbpelegrini** [comment]
`
class Validator:
    def execute(schema, json):
        
        validator = jsonschema.Draft202012Validator(schema)
        
        for error in sorted(validator.iter_errors(json), key=str):
            message = error.message
`

**Comment by Julian** [comment]
You haven't enabled format validation, so both your oneOf schemas always match any string (sounds like the other site you tried isn't fully compliant with the spec). See the FAQ in the docs for how to do so.

**Comment by Julian** [comment]
More specifically https://python-jsonschema.readthedocs.io/en/stable/validate/#validating-formats

**Comment by lbpelegrini** [comment]
That was exactly the problem, thank you so much for the support.

**Comment by Julian** [comment]
Glad to hear, my pleasure! (Sorry, this is obviously something that trips up everyone essentially, but it's spec'ed behavior...)
