### ISSUE TITLE
Self referenced schema encapsulation breaks reference resolution

### ISSUE THREAD

**Issue by andreynovikov** [python-jsonschema/jsonschema#1196]
I have a JSON that by design can contain JSON Schema. I use it at runtime to validate received payload. I have a JSON Schema that describes this JSON:

```json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "code": {
            "type": "string"
        },
        "payload": {
            "$ref": "https://json-schema.org/draft/2020-12/schema",
        }
    }
}
```

When I try to validate my JSON with that schema I get: `jsonschema.exceptions.RefResolutionError: Unresolvable JSON pointer: 'meta'`. It tries to search inner references of `payload` schema in my root schema but not in `$ref`. When I change `payload` ref to:

```json
        "payload": {
            "$ref": "https://json-schema.org/draft/2019-09/schema"
        }
```

validation works as expected.

**Comment by Julian** [comment]
Please share code which reproduces, as both `jsonschema.validate({"payload": {"type": "object"}}, yourschema)` and
`jsonschema.validate({"payload": {"type": "objet"}}, yourschema)` work fine.
