### ISSUE TITLE
Validation error messages changed after upgrading jsonschema version from 3.2.0 to 4.21.1

### ISSUE THREAD

**Issue by saksham99del** [python-jsonschema/jsonschema#1233]
I recently updated my jsonschema version from  3.2.0 to latest one 4.21.1.Since upgrading the version my error messages are changed and i am not able to fix it.

Example Json :
{ "example":
{ "key":"value"}
}
If i change the value of key to key1.I used to get the error message " "key" is a required property " in the earlier version and now after upgrading I am getting the message that prints whole block instead of the affected key like
" "{ "key1":"value"}"  doesn't fulfill the required schema".Is there any way to still get the old message back while still using the latest version.

**Comment by saksham99del** [comment]
Apologies The exact message produced by Library is :
" { 'key1':'value'} is not valid under any of the given schemas" and this change in message is applicable from version 4.8.0 .

**Comment by tanvn** [comment]
I think I have faced the same issue, the previous version provides more informative error messages.

**Comment by saksham99del** [comment]
How did you mitigate the issue?

**Comment by tanvn** [comment]
Ah I just did not upgrade to 4.21.1, we are just using 4.17.x (IIRC 4.18.x also works)
