### ISSUE TITLE
@FormatChecker.checks decorator not a classmethod

### ISSUE THREAD

**Issue by ykursav** [python-jsonschema/jsonschema#1242]
Hello,

I am using jsonschema 4.21.1. When I tried to replace @FormatChecker.cls_checks with @FormatChecker.checks getting below error as it is not @classmethod:

TypeError: FormatChecker.checks() missing 1 required positional argument: 'self'

**Comment by Julian** [comment]
Hi there, it's indeed not a classmethod, it's a thing you need to call on a specific instance of format checker (possibly one for the draft you intend to extend).
