### ISSUE TITLE
Support installation via Homebrew

### ISSUE THREAD

**Issue by aiKrice** [python-jsonschema/jsonschema#1247]
Hello, I saw that this tools was  present in Homebrew but I've got this error:

`Error: jsonschema has been disabled because it cli is deprecated, and will be removed!`

Is it possible to have it up to date <3 

Ty

**Comment by Julian** [comment]
[`check-jsonschema`](https://github.com/python-jsonschema/check-jsonschema) which is the intended replacement is already present via [`brew install check-jsonchema`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/c/check-jsonschema.rb).
