### ISSUE TITLE
Python 3,.13 not yet working due to PyO3 maximum supported version 

### ISSUE THREAD

**Issue by Christian-B** [python-jsonschema/jsonschema#1264]
I know you do not claim that python 3.13 is work yet.
using jsonschema-4.22.0-py3-none-any.whl 

When I tried a github actions install with allow-prereleases python 3.13 I got the error below.

error: the configured Python interpreter version (3.13) is newer than PyO3's maximum supported version (3.12)

I do know this is a dependency not your code directly.

Not a blocker for us.

**Comment by pekkaklarck** [comment]
I noticed Python 3.13 isn't supported as well. I tried to test [Robot Framework](https://github.com/robotframework/robotframework) with Python 3.13, but several tests fail due to jsonschema not being available.

**Comment by Julian** [comment]
There's not much that can be done here, first we need PyO3 support, then we need rpds to be updated to use the newer PyO3 which is a bit of nontrivial work. I waffle about even keeping these kinds of issues open given there's nothing to do here, but will leave it for a bit at least before deciding.

**Comment by Christian-B** [comment]
I would appreciate if this issue is left open so we can track what strategy the jsonschema team are following in regard to Python 3.13.

Waiting for  PyO3 and rpds to be updated is a valid strategy at this point in the Python 3.13 life-cycle.

**Comment by Christian-B** [comment]
Thank you. I can confirm this is now working for me,
