### ISSUE TITLE
Relative pointers fail to evaluate

### ISSUE THREAD

**Issue by stefanklug** [python-jsonschema/jsonschema#1265]
Hi all,

first thanks for this great module.
I'm pretty new to json schema, so bear with me if I got something wrong.
I try to use a relative pointer. According to https://opis.io/json-schema/2.x/pointers.html#relative-pointers
this should be a valid schema definition, but I get a jsonschema.exceptions._WrappedReferencingError.

My failing testcase is:
```
import json
import jsonschema

raw_schema = r'''
{
  "type": "object",
  "properties": {
    "first_email": {
      "type": "string",
      "format": "email"
    },
    "second_email": {
      "$ref": "1/first_email"
    }
  }
}
'''

raw_doc = '''
{"first_email": "john@example.com", "second_email": "opis@example.com"}
'''

schema = json.loads(raw_schema)
doc = json.loads(raw_doc)

# this should succeed, but fails with jsonschema.exceptions._WrappedReferencingError: Unresolvable: 1/first_email
jsonschema.validate(doc, schema)
```
This was tested with version 4.22.0

Is this behavior expected?

Kind regards,
Stefan

**Comment by Julian** [comment]
Hey! Thanks for the kind words. 

 Yes no current version of JSON Schema supports relative pointers anywhere other than in the format keyword.

**Comment by Julian** [comment]
More specifically the PHP page you linked seems simply incorrect under the spec.

**Comment by stefanklug** [comment]
Oh bad luck, so this is actually no bug and I have to put everything under $defs. Correct?

**Comment by Julian** [comment]
It doesn't have to go in `$defs`, you could also use `$anchor`s but yeah there's no such thing as relative referencing right now.

**Comment by stefanklug** [comment]
Thanks for your quick help :smile:
