### ISSUE TITLE
4.22 fails with pytest, black and so on

### ISSUE THREAD

**Issue by gsemet** [python-jsonschema/jsonschema#1266]
hello. it seems like the new version break lot of dependencies with pytest:

```code
    from jsonschema.exceptions import FormatError
.venv/lib/python3.10/site-packages/jsonschema/exceptions.py:15: in <module>
    from referencing.exceptions import Unresolvable as _Unresolvable
E   ModuleNotFoundError: No module named 'referencing'
=================================================================
```

I also see errors with rpds,...

**Comment by Julian** [comment]
I'm not sure what you mean, but this repository does not use pytest, and you haven't included any information (and in general the only supported development environment is via what's here in the repository -- meaning I will only give you help with a development setup using the development setup used here in the repository via nox, regardless of the fact that I do intend for other setups to work). Please feel free to follow up with an actual bug report.
