### ISSUE TITLE
"email" format validation is too relaxed

### ISSUE THREAD

**Issue by trzejos** [python-jsonschema/jsonschema#1284]
The validator only checks that "@" is in the input string, rather than one of the specifications for the "email" or "idn-email" formats.

https://github.com/python-jsonschema/jsonschema/blob/v4.23.0/jsonschema/_format.py#L238

https://json-schema.org/understanding-json-schema/reference/string#email-addresses

**Comment by Julian** [comment]
This is intentional behavior, [documented here](https://python-jsonschema.readthedocs.io/en/stable/validate/#email) and customizable if you have different needs.
