### ISSUE TITLE
Add validate function that reports JSON file line number in error?

### ISSUE THREAD

**Issue by cdeil** [python-jsonschema/jsonschema#156]
Would it be possible to add a validate function that takes a JSON file name (or file handle or text ... something where line number info is available) and reports the line number if there is an error?

Maybe there's a trick to embed line number info in the dict generated by the JSON parser? Maybe build a second dict with identical structure, but line numbers as values instead of the actual content?

For my use case I don't care about performance (speed, memory), but it would be very helpful to get a line number in the error.

I'm new to JSON schema, so apologies if this is a stupid and impossible feature request.
The same question was asked before by @brunoqc here: https://github.com/Julian/jsonschema/pull/90#issuecomment-16578395.

**Comment by analog-cbarber** [comment]
The JSON decoder from the standard python library does not provide a source location information. I am not aware of one that does.

**Comment by jdkandersson** [comment]
Full disclosure: I'm the maintainer of the package below.

There is now a new Python package that solves this use case: <https://github.com/open-alchemy/json-source-map>

Installation: `pip install json_source_map`

For example,  the following JSON document:
```JSON
{
    "foo": "bar"
}
```

Produces the following source map:

```Pyton
{
    "": Entry(
        value_start=Location(line=0, column=0, position=0),
        value_end=Location(line=2, column=1, position=20),
        key_start=None,
        key_end=None,
    ),
    "/foo": Entry(
        value_start=Location(line=1, column=11, position=13),
        value_end=Location(line=1, column=16, position=18),
        key_start=Location(line=1, column=4, position=6),
        key_end=Location(line=1, column=9, position=11),
    ),
}
```

**Comment by sspTest** [comment]
> > If you combine that with a JSON parser that preserves where that property was in the file, you seem to have what you want.
> 
> Is it possible to do this with the [json](https://docs.python.org/3.5/library/json.html) parser in the Python standard library?

@cdeil did you find any package to get the line number for error cases?
