### ISSUE TITLE
Make it easier to create ref resolvers that don't do any remote lookup

### ISSUE THREAD

**Issue by jaredgrubb** [python-jsonschema/jsonschema#693]
I enjoy using the `$ref` stuff (and `$id`) but I really never want my validators to _actually_ access the network. I used a RefResolver instance to map some schemas together, but I can't  figure out how to permanently disable actual network access (and only use the  local store provided). 

I looked through the sources  and didn't see anything obviously.  If this is already possible, maybe  it'd be worth a FAQ entry or something?

**Comment by Julian** [comment]
It's possible, though not easily and not in a great way. Doing so more easily is part of #346. Happy to keep this open as a way to track the request individually though, it's a common request to make this easier.

**Comment by willson-chen** [comment]
@jaredgrubb Maybe the PR #717 could solve your problem.

**Comment by Julian** [comment]
Hello there!

This, along with many many other `$ref`-related issues, is now finally being handled in #1049 with the introduction of a new [referencing library](https://github.com/python-jsonschema/referencing/) which is fully compliant and has APIs which I hope are a lot easier to understand and customize.

The next release of `jsonschema` (v4.18.0) will contain a merged version of that PR, and should be released shortly in beta, and followed quickly by a regular release, assuming no critical issues are reported.

The new APIs do not have this bad behavior -- they don't make HTTP requests by default!

If you still care to, I'd love it if you tried out the beta once it is released, or certainly it'd be hugely helpful to immediately install the branch containing this work (https://github.com/python-jsonschema/jsonschema/tree/referencing) and confirm. You can in the interim find documentation for the change in a [preview page here](https://python-jsonschema--1049.org.readthedocs.build/en/1049/referencing/).

I'm going to close this given it indeed seems like it is addressed by #1049, but feel free to follow up with any comments. Sorry for the delay in getting to these, but hopefully this new release will bring lots of benefit!
