### ISSUE TITLE
cleanup of `pretty` output renderer

### ISSUE THREAD

**Issue by sloanlance** [python-jsonschema/jsonschema#708]
Based on a conversation started in the comments of #706, clean up the appearance of the new `pretty` output renderer.  Pertinent points from the conversation…

* [x] Fix length of the output dividers (current length is arbitrary; the length of `=` and `-` lines do not match)
* [x] Change to Unicode box characters from ASCII
* [x] Add vertical space between each error
* [x] Change exception messages from Python object `repr`s (with single-quoted strings) to true JSON (with double-quoted strings)

<details>
<summary>Details</summary>
I think more important than adding even more output renderers is essentially cleaning up the one new one that was added. Specifically, here's some example output from the new pretty renderer:

```
⊙  printf '7' | jsonschema --output pretty <(printf '{"minimum": 9, "multipleOf": 3, "not": {"const": 7}}')

===[ValidationError]===(<stdin>)===

7 is less than the minimum of 9

Failed validating 'minimum' in schema:
    {'minimum': 9, 'multipleOf': 3, 'not': {'const': 7}}

On instance:
    7
-----------------------------
===[ValidationError]===(<stdin>)===

7 is not a multiple of 3

Failed validating 'multipleOf' in schema:
    {'minimum': 9, 'multipleOf': 3, 'not': {'const': 7}}

On instance:
    7
-----------------------------
===[ValidationError]===(<stdin>)===

{'const': 7} is not allowed for 7

Failed validating 'not' in schema:
    {'minimum': 9, 'multipleOf': 3, 'not': {'const': 7}}

On instance:
    7
-----------------------------
```

where some things that rub me a bit wrong visually are:

* the width of the ascii dividers (right now it's a bit arbitrary and you can see it doesn't match between the `=` and `-` lines -- particularly so if it's a `SchemaError` vs a `ValidationError`)
* not using unicode box characters
* needing a bit of vertical space between each error
* the fact that, though it's not obvious there, in the exception message, what's there is reprs of Python objects. Even though usually that's what I _want_ shown because jsonschema normally deals with Python objects, not JSON, here that's _not_ the case -- here in fact the reverse is true -- the CLI takes JSON, and does the deserialization itself. So when showing errors back to users of the CLI, it should show JSON, not Python objects.
</details>

**Comment by sloanlance** [comment]
What do you think of this output, @Julian, with divisions padded to a width of 79 characters per line?

```
╒══[ValidationError]═══(<stdin>)══════════════════════════════════════════════╕
7 is less than the minimum of 9

Failed validating 'minimum' in schema:
    {'minimum': 9, 'multipleOf': 3, 'not': {'const': 7}}

On instance:
    7
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

╒══[ValidationError]═══(<stdin>)══════════════════════════════════════════════╕
7 is not a multiple of 3

Failed validating 'multipleOf' in schema:
    {'minimum': 9, 'multipleOf': 3, 'not': {'const': 7}}

On instance:
    7
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

╒══[ValidationError]═══(<stdin>)══════════════════════════════════════════════╕
{'const': 7} is not allowed for 7

Failed validating 'not' in schema:
    {'minimum': 9, 'multipleOf': 3, 'not': {'const': 7}}

On instance:
    7
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

```

The footer looks long here, but comes out right in a terminal.

**Comment by Julian** [comment]
Very nice! Definitely an improvement! Thumbs up from me.

**Comment by sloanlance** [comment]
Perhaps off-topic:  The error message '{'const': 7} is not allowed for 7' seems odd.  Unlike the other two messages in this example, the value being tested (7) comes at the end of the statement and the JSON code seems unnecessary.  I think a better error message would be simply `7 is not allowed`.

If you agree, should this be a new issue, or would it be OK for me to change it as part of this issue and PR?

**Comment by Julian** [comment]
I agree on the awkwardness -- let's tackle it in a new issue -- the thing that is a bit complicated is that what's involved there is less about `const` and more about `not` -- `not` needs a message suitable to invert any condition (schema). So in general it's not easy to have that / know what schema you're inverting. Here of course when it's const it's obvious what better looks like, but `not` won't know that in general. But yeah definitely if we can find a way to not terribly overcomplicate things I'm all for it.

**Comment by sloanlance** [comment]
I'll open a new issue for the "not" error message issue.

**Comment by Julian** [comment]
Superceded by [check-jsonschema](https://github.com/python-jsonschema/check-jsonschema) which is now the official (and more-featureful) CLI. Anyone interested in this is invited to have a look there (and file any issues necessary).
