### ISSUE TITLE
TypeError from re for non-string keys

### ISSUE THREAD

**Issue by HeptaSean** [python-jsonschema/jsonschema#788]
When the instance contains non-string keys in a dictionary and they are checked by the re module, because there are patternProperties defined, the TypeError from re.search is neither prevented nor catched:
```python
>>> import jsonschema
>>> jsonschema.validate({42: 42}, {'patternProperties': {'.*': {}}})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/test-venv/lib/python3.9/site-packages/jsonschema/validators.py", line 932, in validate
    error = exceptions.best_match(validator.iter_errors(instance))
  File "/tmp/test-venv/lib/python3.9/site-packages/jsonschema/exceptions.py", line 367, in best_match
    best = next(errors, None)
  File "/tmp/test-venv/lib/python3.9/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/tmp/test-venv/lib/python3.9/site-packages/jsonschema/_validators.py", line 22, in patternProperties
    if re.search(pattern, k):
  File "/usr/lib/python3.9/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```

The standard library JSON module allows int, float, bool and None keys in addition to strings (although ECMA-404 only allows strings):
```python
>>> import json
>>> json.dumps({42: 42, 42.42: 42.42, True: True, None: None})
'{"42": 42, "42.42": 42.42, "true": true, "null": null}'
```

I would expect jsonschema to either disallow non-string keys completely (and, hence, raise a ValidationError before they are even given to the re module) in accordance with ECMA-404 or do the same conversions to strings as the standard library before doing any further checks.

**Comment by Julian** [comment]
The standard library *dumps* non-string valued dicts by coercing them to JSON first and then dumping that.

It will never *load* back a dict that can't come from valid JSON (which is what a dict with int-valued keys is).

**Comment by HeptaSean** [comment]
Agreed that this can't happen with instances loaded from valid JSON. (And I also have the feeling that the behaviour of the standard library – allowing non-string keys for dumping – is a little odd here.)

I stumbled upon this while looking for edge cases to test my code for.

Should I assume that jsonschemas behaviour is undefined for instances that were not loaded from valid JSON (but, e.g., programmatically created to later be serialised)? Even if they would be accepted by json.dump(s) – and loaded back with this strange implicit string conversion?

In jsonschema, we are validating Python objects representing instances against Python objects representing schemas. To me both approaches would make sense: Assume that both were already loaded from valid JSON files/strings – won't fix for this issue. Or validate as if both were dumped to valid JSON files/strings – then it should be fixed.

**Comment by Julian** [comment]
> Should I assume that jsonschemas behaviour is undefined for instances that were not loaded from valid JSON (but, e.g., programmatically created to later be serialised)? Even if they would be accepted by json.dump(s) – and loaded back with this strange implicit string conversion?

So I'd love to make this clearer certainly so that folks don't have to assume anything. I could have sworn it was in the docs already but I don't see it (though I'm on calls so I may not be seeing it where I expect).

"Officially" the type of the `instance` argument is a bit clunky, but it's "things you could have gotten back from `json.load(s)`" yeah. If you give it something else it's undefined where that may error.

> Assume that both were already loaded from valid JSON files/strings – won't fix for this issue. Or validate as if both were dumped to valid JSON files/strings – then it should be fixed.

It would "fix" this issue but break others. E.g. `jsonschema` supports: `jsonschema.validate({"foo": decimal.Decimal(12)}, ...)` if you tell it that `decimal.Decimal` instances are numbers. But it doesn't keep any information on how to call `json.dumps` on arbitrary objects it's given, it just keeps type information.
