### ISSUE TITLE
uritemplate v4 update dropped support for python 2 applications

### ISSUE THREAD

**Issue by claudinoac** [python-jsonschema/jsonschema#859]
Hi,
I'm running this library on a python 2 application in version 3.2.0 and 
the package uritemplate was updated to v4.
It is now breaking my application with a syntax error, since uritemplate v4 dropped support to python 2 [here](https://github.com/python-hyper/uritemplate/commit/ec8664c83f052b92ac0eeacc037619bac800a6d1) 
I suggest you guys to pin this package on v3.0.1, which still supports python 2.

**Comment by Julian** [comment]
Hi there. There wouldn't be any future Python2-supporting releases of this package, so it wouldn't help you even if this were done.

You should pin uritemplate in your own application, and/or ensure that upstream, uritemplate has properly declared `python_requires` such that your package installer (`pip`) does not try to install versions of it that don't support the version of Python you're using.
