### ISSUE TITLE
CLI does not accept a schema without instance any longer

### ISSUE THREAD

**Issue by krassowski** [python-jsonschema/jsonschema#889]
Hi, thanks for maintaining `jsonschema`! We were using `jsonschema` to validate the integrity of the schema itself (i.e. is it a valid schema) as an early step in CI in https://github.com/python-lsp/python-lsp-server/ (if schema is not valid, we want to short-circuit early). When upgrading CI from Python 3.6 (which was pulling `jsonschema` 3.2.0) to a newer Python version (resolving `jsonschema` to 4.2.1) on https://github.com/python-lsp/python-lsp-server/pull/130 the CI started failing:

```
jsonschema pylsp/config/schema.json
Failed to parse <stdin>: Expecting value: line 1 column 1 (char 0)
```

I did not find a changelog entry warning about to this change, but comparing `jsonschema -h` between versions I see that `-i` option is no longer really optional (i.e. it is now implicitly required):

3.2.0:

```
usage: jsonschema [-h] [-i INSTANCES] [-F ERROR_FORMAT] [-V VALIDATOR] [--version] schema

JSON Schema Validation CLI

positional arguments:
  schema                the JSON Schema to validate with (i.e. schema.json)

optional arguments:
  -h, --help            show this help message and exit
  -i INSTANCES, --instance INSTANCES
                        a path to a JSON instance (i.e. filename.json) to validate (may be specified multiple times)
```

4.2.1:

```
usage: jsonschema [-h] [-i INSTANCES] [-F ERROR_FORMAT] [-o {plain,pretty}] [-V VALIDATOR] [--base-uri BASE_URI] [--version] schema

JSON Schema Validation CLI

positional arguments:
  schema                the path to a JSON Schema to validate with (i.e. schema.json)

optional arguments:
  -h, --help            show this help message and exit
  -i INSTANCES, --instance INSTANCES
                        a path to a JSON instance (i.e. filename.json) to validate (may be specified multiple times).
                        If no instances are provided via this option, one will be expected on standard input.
```

the addition of `If no instances are provided via this option, one will be expected on standard input.` forces users to always pass a valid instance via standard input if they want to validate the schema itself.

One solution could be to add `--no-instances` optional argument (in 4.x). Another would be to just pass if no instance is given. What do you think?

For posterity coming here from search engines, I will cross-reference https://github.com/Julian/jsonschema/issues/888 (although not asking about CLI, this issue could answer the question from the title of the other one).

**Comment by Julian** [comment]
Hi! Thanks for the kind words.

This is probably an oversight (or, well, something that a test was missing for, so yeah an unintentional oversight in reworking the CLI). #643 is I think the relevant PR.

I'm not so keen on a `--no-instances` argument initially -- so I'm not sure what a fix looks like yet, but I'm certainly willing to fix this *somehow*. Another option is forcing someone to pass `-` to indicate stdin, but that'd now be another breaking change... Not sure. Will have to think, but feel free to share any additional thoughts.

**Comment by sirosen** [comment]
In this case, the schema is being validated under a relevant metaschema.
So rather than `--no-instances` ("don't do X"), is there a positive phrasing ("do Y") like `--check-metaschema`?

`jsonschema pylsp/config/schema.json --check-metaschema`

**Comment by Julian** [comment]
Any flag I think will cause annoyance -- namely it will introduce the need for mutually exclusive options (`--check-metaschema` and `-i`), or it will make `--check-metaschema`'s behavior confusing if it's normally implied by `-i`.

I'm still somewhat personally leaning towards reverting the read from `stdin` such that one can go back to providing no instances, but supporting reading from stdin by passing `-` as the instance as many CLI tools tend to. I suspect a PR implementing this would be acceptable.

More ideas are good though as well.

**Comment by sirosen** [comment]
I've implemented this as a `--check-metaschema` flag in `check-jsonschema`. Because I already need to deal with mutex options there, it wasn't too much of an additional burden.

It is a bit of a mouthful to write `check-jsonschema --check-metaschema foo.json`, but at least it's clear and explicit.

_I am the author of `check-jsonschema` and we are currently discussing making it the official CLI for `jsonschema`. For details, you can follow #910. If `check-jsonschema` has a behavior which you believe should be changed to handle your use-case, please [open an issue](https://github.com/sirosen/check-jsonschema/issues/new)!_

**Comment by sirosen** [comment]
We're going to move forward and begin calling `check-jsonschema` the official CLI. I'm therefore closing this as a wontfix.

Definitely let me know if you'd like a hand updating python-lsp-server to use `check-jsonschema` where you're using `jsonschema`'s built-in CLI. I'm happy to stop by and see how I can help.
