### ISSUE TITLE
Validate date-time via CLI

### ISSUE THREAD

**Issue by ianyoung** [python-jsonschema/jsonschema#913]
This is not so much of an issue but a question regarding how to validate against the date format when run via the CLI.

I've installed `jsonschema` with the `[format]` extras:

`pipenv install "jsonschema[format]"`

I've also installed `strict-rfc3339` and `rfc3339-validator`, although I'm not sure if they're required in addition to the format extras(?):

```
[packages]
jsonschema = {extras = ["format"], version = "*"}
strict-rfc3339 = "*"
rfc3339-validator = "*"
```

In my schema file I have the following validation and am working to a JSON Schema Draft 04 spec:

```
"instructionDate": {
    "type": "string",
    "format": "date-time",
    "examples": [
        "2021-11-08T08:33:19+00:00"
    ]
},
```

When I run the validation via the CLI I'm not sure which validator to pass in:

`pipenv run jsonschema -i data.json json-schema.json -V rfc3339-validator`

I receive the following error in STDOUT:

`AttributeError: module jsonschema has no attribute rfc3339-validator`

I couldn't find any reference in the docs for which validator to pass in. Are you able to clarify?

**Comment by ianyoung** [comment]
I've tried `Draft7Validator` and `Draft4Validator`. Neither result in any errors so I presume this is the correct format? However, they also don't appear to be correctly validating my date field.

With the following input in `data.json`:
```
"instructionDate": "X",
```

And the format as set above:
```
"instructionDate": {
    "type": "string",
    "format": "date-time"
},
```
jsonschema runs without any errors:
```
pipenv run jsonschema -i data.json json-schema.json -V Draft4Validator
```

**Comment by ianyoung** [comment]
Thanks @sirosen. That helps to explain the issue and provide an alternative, and hopefully long-term solution.

For the time being I've reverted to a regex `"pattern"` match but I'd love to remove that and use the in-built format validation. Thanks for raising awareness of [check-jsonschema](https://github.com/sirosen/check-jsonschema). I look forward to seeing the best of both worlds combine. :)

**Comment by sirosen** [comment]
To clarify, `check-jsonschema` is not going to merge into the `jsonschema` package. It's going to remain separate, with its own versions and releases, as a consumer of the underlying `jsonschema` package.

**Comment by sirosen** [comment]
We're now considering `check-jsonschema` the official CLI, so I'm going to close this as a "wontfix". The `jsonschema` CLI will not gain new capabilities in this space.
