### ISSUE TITLE
RefResolver should support in-schema and external refs at the same time

### ISSUE THREAD

**Issue by reitzig** [python-jsonschema/jsonschema#916]
I **expect** to be able to use both internal (i.e. the same file) and external (i.e. other files) references in the same schema. As far as I can tell,

 - without an explicit `RefResolver` internal references work but external ones don't, and
 - `jsonschema.RefResolver(f"{schema_file.parent.absolute().as_uri()}/", None)` works for relative filesystem references.

Unfortunately, that resolver **actually** breaks internal references.

[MWE](https://gist.github.com/reitzig/383509b990c5547be47e8767fe021381) (the failing cases for `example.schema.json`)

**Workaround**: Repeat the name of the current file in `"$ref"`, making it an external reference.

### Side notes

 - The issue/request actually extends to using _remote_ references as well.
 - The behaviour of `RefResolver` doesn't seem to be very well documented; I had to scrounge together advice from comments on issues.
 - Specifically, I _think_ providing `handlers` might do what I want, but there's unfortunately no documentation on how to use that parameter.
 - And, honestly, I'd expect the library to handle the usual cases of `"#/definitions/stuff"`, `"file.schema.json"#/definitions/stuff"`, and `"http(s)://abc.def/file.schema.json#/definitions/stuff"` by default.

**Comment by mdavis-xyz** [comment]
> without an explicit RefResolver internal references work

Do they? How? I'm trying to figure out how to do that, and I can't. Can you provide a minimal working example, or an explanation?
