### ISSUE TITLE
Please bring back setup.py

### ISSUE THREAD

**Issue by AddisonG** [python-jsonschema/jsonschema#929]
The [Embedded Linux Distro Yocto](https://www.yoctoproject.org/), uses a build system called [Bitbake](https://www.yoctoproject.org/docs/1.6.1/bitbake-user-manual/bitbake-user-manual.html). It seems that we require `setup.py` to be required for us to create dependencies on `jsonschema` when using Bitbake.

Because it was removed as part of 112c809e7e3574528b2c2b908bf0add4130af586, we can no longer build anything past `v3.2.0`, as our builds fail with:

```
ERROR: python3-jsonschema-4.4.0-r0 do_compile: 'python3 setup.py build ' execution failed.
ERROR: python3-jsonschema-4.4.0-r0 do_compile: Execution of '/home/......./python3-jsonschema/4.4.0-r0/temp/run.do_compile.504103' failed with exit code 1
ERROR: Logfile of failure stored in: /home/........./python3-jsonschema/4.4.0-r0/temp/log.do_compile.504103
Log data follows:
| DEBUG: Executing shell function do_compile
| /home/........../python3-jsonschema/4.4.0-r0/recipe-sysroot-native/usr/bin/python3-native/python3: can't open file 'setup.py': [Errno 2] No such file or directory
| ERROR: 'python3 setup.py build ' execution failed.
```

I cannot quite understand what harm there was with `setup.py` being part of this repo, or why it was removed, as the commit message simply reads:
> setup.py is dead

I don't know how many other people are still using setup.py, but I suspect that I'm not the only one who is feeling the loss of it.

From the [setuptools doco](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html):
> If compatibility with legacy builds (i.e. those not using the [PEP 517](https://peps.python.org/pep-0517/) build API) is desired, **a setup.py file containing a setup() function call is still required even if your configuration resides in setup.cfg**.

Could we please re-instate the setup.py file, if it's not actively harming this repo? It will increase compatibility and accessibility, and how many people are able to use the latest versions of jsonschema.

**Comment by Julian** [comment]
Hi there. It's unlikely this will happen unfortunately, though I sympathize.

jsonschema is moving towards even more different packaging tooling such as poetry or flit.

PEP517 has been out for a few years now, and there's plenty of good tooling like [build](https://github.com/pypa/build) to leverage.

As a last resort if you're trying to hack something together you could of course plop down a trivial setup.py during your build process, but as I say, it's unlikely things will change here -- there's by now a very sizable part of the Python ecosystem using more modern packaging tools, so undoubtedly jsonschema won't be the only issue you run into here.
