### ISSUE TITLE
Unable to get jsonschema version using recommended method

### ISSUE THREAD

**Issue by bhilbert4** [python-jsonschema/jsonschema#934]
Hi,

I'm currently using version 4.4.0 on my linux server, and trying to programmatically find the version number. However, jsonschema.\_\_version\_\_ returns None, and when I try the method recommended by the DeprecationWarning, it also returns None. However, when I try the same on my Mac, both methods successfully return "4.4.0".

Linux server:
```
    > import jsonschema
    > jsonschema.__version__
    
    <ipython-input-3-d84b7d4ea6c1>:1: DeprecationWarning: Accessing jsonschema.__version__ is deprecated and will be removed in a future release. Use importlib.metadata directly to query for jsonschema's version.
  jsonschema.__version__
  
    > from importlib.metadata import version
    > version('jsonschema')

    > type(version('jsonschema'))

    NoneType
```

Mac:
```
    In [1]: import jsonschema
    In [2]: jsonschema.__version__

    <ipython-input-3-d84b7d4ea6c1>:1: DeprecationWarning: Accessing jsonschema.__version__ is deprecated and will be removed in a future release. Use importlib.metadata directly to query for jsonschema's version.
  jsonschema.__version__
    Out[3]: '4.4.0'

    In [4]: from importlib.metadata import version
    In [5]: version("jsonschema")
    Out[5]: '4.4.0'
```

thanks,
Bryan

**Comment by Julian** [comment]
Hi -- can you show how you installed jsonschema? Or provide any way to reproduce the behavior you're seeing?

**Comment by bhilbert4** [comment]
Hmm. I checked on a different machine and everything worked fine. I tried uninstalling and reinstalling jsonschema on the original machine, and now it is giving the version number back correctly. I'm not sure why the original install didn't seem to be working correctly, but it seems to be ok now.

**Comment by Julian** [comment]
Glad to hear it's working now then!
