### ISSUE TITLE
Using version 4.4.0 jsonschema with DMTF schema EventDestination.v1_7_0.json will show SchemaError

### ISSUE THREAD

**Issue by FelixD999** [python-jsonschema/jsonschema#938]
Hi,
After I send command below, the respond displayed SchemaError in fist line:
![4 4 0_SchemaError](https://user-images.githubusercontent.com/85208691/165700988-30fef2a3-2665-4dd0-bf82-230dc976e495.JPG)
Not sure if it is the cause in newer version as it does not have this problem in the older version(3.2.0).

Test json file attached for refer:
[123.zip](https://github.com/python-jsonschema/jsonschema/files/8580540/123.zip)

Thanks.

**Comment by Julian** [comment]
Hi. The message is telling you deprecated needs to be a boolean, which indeed it needs to be in Draft 2020-12. I'm not sure what the question you're asking is, but you're comparing behavior across different drafts of the spec, so indeed behavior will differ. If your schema is written for draft 7 you should likely ensure you're specifically using draft 7, perhaps by declaring `$schema`.
