### ISSUE TITLE
Validating against word "type" fails

### ISSUE THREAD

**Issue by RichardMore** [python-jsonschema/jsonschema#943]
I am trying to validate data that includes the word type so validation failed. Here is an example:
`{
   "data": {
       "attributes": {
           "amount_display": "$0.0040",
           "amount_nanodollars": "4000000",
           "body": "Final test",
           "direction": "inbound",
           "from": "12067392634",
           "is_mms": false,
           "message_callback_url": "https://somnxp1g47.execute-api.us-west-2.amazonaws.com/dev/sms_to_slack",
           "message_encoding": 0,
           "message_type": "longcode",
           "status": "delivered",
           "timestamp": "2017-11-16T23:45:29.37Z",
           "to": "12012673227"
       },
       "id": "mdr2-3a353498cb2811e7afa11ade1e71c584",
       "type": "message"
   }
}`

I have the following validation schema now that fails:
`flowrouteSchema = {
        "type": "object",
        "properties": {
                "data": {
                        "attributes": {
                                "amount_display": "string",
                                "amount_nanodollars": "string",
                                "body": "string",
                                "direction": "string",
                                "from": "string",
                                "is_mms": "boolean",
                                "message_callback_url": "string",
                                "message_encoding": "integer",
                                "message_type": "string",
                                "status": "string",
                                "timestamp": "string",
                                "to": "string"
                        },
                        "id": "string",
                        "type": "string"
                }
        }
}`

The part with "type": "string" is what failed with the exception:
jsonschema.exceptions.SchemaError: {'type': 'string'} is not valid under any of the given schemas

Is there any way around this?

**Comment by Julian** [comment]
Hi. There should be no issue with having properties called `type`. Your schema doesn't have a `properties` validator in it though (instead it has `id` and `attributes` keys, not sure what you mean those to do). I'd recommend reviewing https://json-schema.org/understanding-json-schema/reference/object.html and asking either on the JSON Schema Slack or in a discussion if you're having trouble authoring a schema for your objects.
