### ISSUE TITLE
v4.5.1 is missing from CHANGELOG.rst

### ISSUE THREAD

**Issue by lurch** [python-jsonschema/jsonschema#955]
...which is a little bit surprising :wink: 

https://github.com/python-jsonschema/jsonschema/releases vs. https://github.com/python-jsonschema/jsonschema/blob/main/CHANGELOG.rst

**Comment by sirosen** [comment]
I'll put in a PR for this. If I followed correctly, 4.5.1 was a patch to revert a change from 4.5.0 which was a performance regression. (#941)
