### ISSUE TITLE
Unable to use recent versions of jsonschema from typed code (mypy)

### ISSUE THREAD

**Issue by ssbarnea** [python-jsonschema/jsonschema#963]
As the wrapper `types-jsonschema` went out of sync, is no longer possible to use it with mypy. Attempts to use the library directly gives errors because `py.typed` marker was removed.

```
src/ansible_compat/schema.py:6: error: Skipping analyzing "jsonschema": module is installed, but missing library stubs or py.typed marker
src/ansible_compat/schema.py:6: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
src/ansible_compat/schema.py:7: error: Skipping analyzing "jsonschema.validators": module is installed, but missing library stubs or py.typed marker
```

Looking at https://pypi.org/project/types-jsonschema/#history I see that these releases are 2 versions behind as the current version is `4.6.0`

Can we please start publishing types with the library?

Related:
* https://github.com/python-jsonschema/jsonschema/pull/954
* https://github.com/sirosen/jsonschema/commit/ded065d324064a28019739f7478d29b021b687dd which reverted the previous change, apparently not via a pull request.

**Comment by Julian** [comment]
https://github.com/python-jsonschema/jsonschema/pull/954#issuecomment-1136342244 was fairly clear about what the next steps are here. Again, help is welcome.
