### ISSUE TITLE
Memory leak with `jsonschema.validators.validate`

### ISSUE THREAD

**Issue by thientzsch** [python-jsonschema/jsonschema#966]
Apparently, `jsonschema.validators.validate` has a memory leak:
```python
# python 3.10.4
# jsonschema 4.6.0

from jsonschema.validators import validate

def growth() -> str:
    from io import StringIO
    output = StringIO()
    import objgraph
    objgraph.show_growth(limit=100, file=output)
    return output.getvalue()


growth_msg = None
for i in range(1, 10):
    validate("abc", {'type': 'string'})
    growth_msg = growth()
    print(f"{i}. run")
    print(growth_msg)

assert not growth_msg, "memory leak!"

# tuple                 10781       +11
# dict                  18588        +6
# list                   9078        +5
# cell                   2907        +4
# function              17282        +2
# _lru_cache_wrapper       71        +2
# method                  995        +1
# URIDict                  11        +1
# RefResolver              10        +1
```

**Comment by Julian** [comment]
Hi. Do you observe memory growth in some more involved program? And/or is said growth unbounded?

Off the top of my head, `jsonschema` indeed caches things like ref resolution, so I wouldn't expect memory usage to be constant.

**Comment by thientzsch** [comment]
The same growth as in the above reduced snippet also occurs when the validation is used in a program with a more complex json schema.
After closer testing, I find that the growth stops after more than 128 calls to method `validate`, so there is no unlimited growth.
The issue can be closed since it appears to be a false positive memory leak.
