### ISSUE TITLE
Fields order is not preserved in Exceptions

### ISSUE THREAD

**Issue by MazokuMaxy** [python-jsonschema/jsonschema#968]
Its not that big deal but it could be nice if error preserve the order of properties. 
```
>>> jsonschema.validate(
...     instance={'d':'1'},
...     schema={
...         'type': 'object', 
...         'properties': {
...             'c': {'type':'string'},
...             'a': {'type':'string'},
...             'b': {'type':'string'},
...         },
...         'additionalProperties': False,
...     }
... )

jsonschema.exceptions.ValidationError: Additional properties are not allowed ('d' was unexpected)

Failed validating 'additionalProperties' in schema:
    {'additionalProperties': False,
     'properties': {'a': {'type': 'string'},
                    'b': {'type': 'string'},
                    'c': {'type': 'string'}},
     'type': 'object'}

On instance:
    {'d': '1'}
```

**Comment by Julian** [comment]
This is passed along behavior from [`pprint.pformat`](https://docs.python.org/3/library/pprint.html#pprint.pformat) which sorts dicts by default. Of course we could set that to `False` -- I agree with you that there are cases where if you typed in a dict literal it shouldn't sort, but I suspect the more common case has sorting be helpful. If you got a dict from somewhere (e.g. over a socket or from a file) and don't know what layout it has, sorted keys make it easier to find what you're looking for, so I suspect changing the default there will help some cases but hurt others. Happy to hear feedback though.
