### ISSUE TITLE
DeprecationWarning: Passing a schema to Validator.is_valid is deprecated

### ISSUE THREAD

**Issue by jamesstidard** [python-jsonschema/jsonschema#976]
Hi,

I was hoping for some help resolving this depreciation warning. I'm not sure what the new intended structure is, and not been able to see it in the documentation. I believe this method is still not depreciated in the documentation.

```python
from jsonschema import Draft7Validator, validators

extensions = {}
validator_cls = validators.extend(validator_cls, extensions)
validator = validator_cls(schema=schema, resolver=resolver)
validator.iter_errors(instance)
```

At the moment this has started to yield these warnings:

```console
DeprecationWarning: Passing a schema to Validator.iter_errors is deprecated and will be removed in a future release. Call validator.evolve(schema=new_schema).iter_errors(...) instead.
  for error in validator.iter_errors(instance, properties):

DeprecationWarning: Passing a schema to Validator.is_valid is deprecated and will be removed in a future release. Call validator.evolve(schema=new_schema).is_valid(...) instead.
  elif validator.is_valid(instance, EQUATION_SCHEMA):
````

I've not been able to wrap my head around what changes are needed here, and the methods I've tried will either return the same warning, or are just incorrect usage of the API.

Would appreciate some pointers,
cheers.

**Comment by Julian** [comment]
Hi. That code looks incomplete (it's got name errors) -- even if the name errors were fixed though it shouldn't produce any deprecation warnings.

The warnings seem to point to some extensions you've got though, ones which indeed are calling `iter_errors` with 2 arguments. The replacement is in the message -- call `validator.evolve(schema=new_schema).iter_errors(instance) instead` rather than `validator.iter_errors(instance, new_schema)`.

**Comment by jamesstidard** [comment]
@Julian 

> The warnings seem to point to some extensions you've got though

Ah, this was he bit that was escaping me. Thank you for catching that. I thought the error was coming from that .iter_errors call, not one from the extension. Feel a little silly now. Solved, thank you for your time.

**Comment by Julian** [comment]
No problem.
