### ISSUE TITLE
Reference to local files (with relative/no path) doesn't work

### ISSUE THREAD

**Issue by sblask** [python-jsonschema/jsonschema#98]
I am trying to create a json schema (draft 4) which uses definitions from another file and includes them using $ref. I don't have any URL set up for the definitions file and I wasn't planning on doing that. I thought "$ref": "definitions.json#a_definition" (definitions.json lying in the same directory) would be enough, but I get a "No such file or directory" error.

I am not sure this should work, but this: http://code.google.com/p/jsonschema2pojo/wiki/Reference#$ref suggests it should ("$ref" : "user.json"). Googling/reading the draft didn't get me anywhere.

Using file://absolute/path/to/json/file does work, but that would be super ugly. Is there a better way to do what I want to do? Or is this something that needs fixing?

**Comment by iandanforth** [comment]
@sblask Has the best answer so far. Here's a slight modification that more closely conforms to the intent of the source.

    import os
    import json
    import jsonschema

    schema_path = os.path.join(absolute_path_to_base_directory, base_filename)
    with open(schema_path) as file_object:
        schema = json.load(file_object)

    # Note that the second parameter does nothing.
    resolver = jsonschema.RefResolver('file://' + absolute_path_to_base_directory + '/', None)

    # This will find the correct validator and instantiate it using the resolver.
    jsonschema.validate(data, schema, resolver=resolver)

**Comment by mottosso** [comment]
I spent the better part of a morning struggling with this on Windows, so thought I'd share in case anyone else runs into the same issue.

@sblask solution works well, with the one caveat that the `absolute_path..` needs forward-slashes, as opposed to default back-slashes, and `file://` needing an extra `/`.

I got it working with this.

```python
with open(os.path.join(absolute_path_to_base_directory, base_filename)) as file_object:
    schema = json.load(file_object)
resolver = jsonschema.RefResolver('file:///' + absolute_path_to_base_directory.replace("\\", "/") + '/', schema)
jsonschema.Draft4Validator(schema, resolver=resolver).validate(data)
```

The extra forward-slash still doesn't make much sense, without it, I'm getting this.

```bash
jsonschema.exceptions.RefResolutionError: <urlopen error file not on local host>
```

And I haven't yet tested it on other platforms.

**Comment by kerlyn-bsd3** [comment]
> The extra forward-slash still doesn't make much sense, without it, I'm getting this.

What is the value of 'absolute_path_to_base_directory'?  Is it missing an initial
forward-slash that designates the root of the file system?

**Comment by clenk** [comment]
I recently encountered this issue but what solved it for me was giving RefResolver the whole filename including the extension, not just the directory.

```
resolver = jsonschema.RefResolver('file://' + absolute_path_to_base_directory + '/' + base_filename, None)
```

**Comment by topher515** [comment]
I had a hard time figuring this out myself, and I kept googling into this github issue. (The solution is pretty much what @clenk says above.)

Here's a SO Q&A which covers it: https://stackoverflow.com/questions/53968770/how-to-set-up-local-file-references-in-python-jsonschema-document

Hopefully this helps someone in the future.

**Comment by koteez** [comment]
Hi, I have the same issue but I was not planning to write my own Python script and more in favor of using the command line and having a parameter. Is there is Draft7 (I am based on that one) a way to override the base_uri ?

**Comment by Julian** [comment]
Probably reasonable to open an issue to discuss whether the CLI needs a way
to specify base URI.

Include a suggestion and/or what you're trying if you can.

**Comment by rwberendsen** [comment]
Hi, is it also possible to load all schema files in jsonschema, independently of their location in the directory structure on disk, and independently of whether they are actually served on network addressable locations over https? Then have jsonschema resolve $refs just by resolving against $id?

 See https://json-schema.org/understanding-json-schema/structuring.html :
 
 "
 Note

Even though schemas are identified by URIs, those identifiers are not necessarily network-addressable. They are just identifiers. Generally, implementations don’t make HTTP requests (https://) or read from the file system (file://) to fetch schemas. Instead, they provide a way to load schemas into an internal schema database. When a schema is referenced by it’s URI identifier, the schema is retrieved from the internal schema database.
"
