### ISSUE TITLE
Is types-jsonschema outdated in typeshed?

### ISSUE THREAD

**Issue by kratsg** [python-jsonschema/jsonschema#997]
I expected the following code to work when it comes to typing

```python
from typing import Any, Mapping
import jsonschema

store: dict[str, Mapping[str, Any]] = {}

jsonschema.RefResolver(
    base_uri=f"file://mypath.json",
    referrer={},
    store=store
)
```

However, this gives an error:

```
test.py:9: error: Argument "store" to "RefResolver" has incompatible type "Dict[str, Mapping[str, Any]]"; expected "Union[SupportsKeysAndGetItem[str, str], Iterable[Tuple[str, str]]]"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

defined at https://github.com/python/typeshed/blob/c1d307fc3bf51488b708e1c71334faccba5fd294/stubs/jsonschema/jsonschema/validators.pyi#L66-L80 . It seems incorrect that `store` is a `dict[str, str]` type.

Similarly, `referrer` is defined as a `dict` (`MutableMapping`) but I suspect that could be changed to `Mapping` (generically).

**Comment by Julian** [comment]
Possibly? Did you mean to file this ticket there?

**Comment by kratsg** [comment]
> Possibly? Did you mean to file this ticket there?

I wasn't completely sure if this was something you maintained or not - so I wanted to check with the project version before filing with `typeshed`.
