### ISSUE TITLE
jsonschema is correctly given ,but validate fail in code 

### ISSUE THREAD

**Issue by rushant001** [python-jsonschema/jsonschema#998]
input json body:
{"error_code": 0, "error_msg": "OK", "result": {"data": [{"action": "to", "mod": "cleaner", "property": "area", "property_unit": null, "property_value": ["1013", "2014"], "reply": "", "skill_id": "1104379", "time_duration": null, "time_start": "2022-09-03|22:00:00"}], "err_code": 0, "err_msg": "ok", "response_list": [{"schema": {"slots": [], "intent_confidence": 100, "intent": "", "domain_confidence": 100}, "origin": "1104379", "action_list": [{"custom_reply": "{"reply":[]}"}]}]}}

input jsonschema:
{"required": ["error_code", "error_msg", "result"], "type": "object", "properties": {"error_code": {"type": "integer"}, "error_msg": {"type": "string"}, "result": {"required": ["data", "err_code", "err_msg", "response_list"], "type": "object", "properties": {"err_msg": {"type": "string"}, "data": {"items": [{"required": ["action", "mod", "property", "property_unit", "property_value", "reply", "skill_id", "time_duration", "time_start"], "type": "object", "properties": {"property_unit": {"type": "null"}, "time_duration": {"type": "null"}, "property_value": {"items": {}, "type": "array"}, "action": {"type": "string"}, "reply": {"type": "string"}, "property": {"type": "string"}, "time_start": {"type": "string"}, "skill_id": {"type": "string"}, "mod": {"type": "string"}}}], "type": "array"}, "response_list": {"items": [{"required": ["schema", "origin", "action_list"], "type": "object", "properties": {"origin": {"type": "string"}, "action_list": {"items": [{"required": ["custom_reply"], "type": "object", "properties": {"custom_reply": {"type": "string"}}}], "type": "array"}, "schema": {"required": ["slots", "intent_confidence", "intent", "domain_confidence"], "type": "object", "properties": {"intent": {"type": "string"}, "slots": {"items": {}, "type": "array"}, "intent_confidence": {"type": "integer"}, "domain_confidence": {"type": "integer"}}}}}], "type": "array"}, "err_code": {"type": "integer"}}}}}

### the code is below:
from jsonschema import validate
ret = validate(instance=response, schema=validate_schema)

### validate returned fail info:
ret = validate(instance=response, schema=validate_schema)
  File "/usr/local/lib/python3.7/site-packages/jsonschema/validators.py", line 1018, in validate
    cls.check_schema(schema)
  File "/usr/local/lib/python3.7/site-packages/jsonschema/validators.py", line 190, in check_schema
    raise exceptions.SchemaError.create_from(error)
jsonschema.exceptions.SchemaError: [{'required': ['schema', 'origin', 'action_list'], 'type': 'object', 'properties': {'origin': {'type': 'string'}, 'action_list': {'items': [{'required': ['custom_reply'], 'type': 'object', 'properties': {'custom_reply': {'type': 'string'}}}], 'type': 'array'}, 'schema': {'required': ['slots', 'intent_confidence', 'intent', 'domain_confidence'], 'type': 'object', 'properties': {'intent': {'type': 'string'}, 'slots': {'items': {}, 'type': 'array'}, 'intent_confidence': {'type': 'integer'}, 'domain_confidence': {'type': 'integer'}}}}}] is not of type 'object', 'boolean'
Failed validating 'type' in metaschema['allOf'][1]['properties']['properties']['additionalProperties']['$dynamicRef']['allOf'][1]['properties']['properties']['additionalProperties']['$dynamicRef']['allOf'][1]['properties']['items']['$dynamicRef']['allOf'][0]:
    {'$defs': {'anchorString': {'pattern': '^[A-Za-z_][-A-Za-z0-9._]*$',
                                'type': 'string'},
               'uriReferenceString': {'format': 'uri-reference',
                                      'type': 'string'},
               'uriString': {'format': 'uri', 'type': 'string'}},
     '$dynamicAnchor': 'meta',
     '$id': 'https://json-schema.org/draft/2020-12/meta/core',
     '$schema': 'https://json-schema.org/draft/2020-12/schema',
     '$vocabulary': {'https://json-schema.org/draft/2020-12/vocab/core': True},
     'properties': {'$anchor': {'$ref': '#/$defs/anchorString'},
                    '$comment': {'type': 'string'},
                    '$defs': {'additionalProperties': {'$dynamicRef': '#meta'},
                              'type': 'object'},
                    '$dynamicAnchor': {'$ref': '#/$defs/anchorString'},
                    '$dynamicRef': {'$ref': '#/$defs/uriReferenceString'},
                    '$id': {'$comment': 'Non-empty fragments not allowed.',
                            '$ref': '#/$defs/uriReferenceString',
                            'pattern': '^[^#]*#?$'},
                    '$ref': {'$ref': '#/$defs/uriReferenceString'},
                    '$schema': {'$ref': '#/$defs/uriString'},
                    '$vocabulary': {'additionalProperties': {'type': 'boolean'},
                                    'propertyNames': {'$ref': '#/$defs/uriString'},
                                    'type': 'object'}},
     'title': 'Core vocabulary meta-schema',
     'type': ['object', 'boolean']}
On schema['properties']['result']['properties']['response_list']['items']:
    [{'properties': {'action_list': {'items': [{'properties': {'custom_reply': {'type': 'string'}},
                                                'required': ['custom_reply'],
                                                'type': 'object'}],
                                     'type': 'array'},
                     'origin': {'type': 'string'},
                     'schema': {'properties': {'domain_confidence': {'type': 'integer'},
                                               'intent': {'type': 'string'},
                                               'intent_confidence': {'type': 'integer'},
                                               'slots': {'items': {},
                                                         'type': 'array'}},
                                'required': ['slots',
                                             'intent_confidence',
                                             'intent',
                                             'domain_confidence'],
                                'type': 'object'}},
      'required': ['schema', 'origin', 'action_list'],
      'type': 'object'}]

**Comment by Julian** [comment]
As the error is saying, in your schema you're passing an array to `items`, but in draft 2020-12, it doesn't take one, it takes only schemas. See https://json-schema.org/draft/2020-12/release-notes.html#changes-to-items-and-additionalitems, you may be looking for `prefixItems`, or perhaps you're not properly specifying which version your schema is intended to be run with via `$schema`.

**Comment by rushant001** [comment]
Thank you sincerely for your reply！
